-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "icc"
local chunkStartIndex = 8646
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["lilrahuul"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][4] = { 5152, 15, 17, 3108 }
			player[9][1][5] = { 7111, 14, 17, 219 }
	end
end
do
	local player = players["datori"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 6255, 91, 104, 8173 }
			player[9][3][5] = { 3586, 92, 105, 4809 }
	end
end
do
	local player = players["nastybear"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 5234, 67, 80, 6912 }
			player[9][1][5] = { 3281, 74, 83, 4049 }
	end
end
do
	local player = players["turboderp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 3978, 93, 111, 5253 }
			player[9][1][5] = { 3192, 75, 84, 3938 }
	end
end
do
	local player = players["duehoof"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 5882, 55, 63, 7768 }
	end
end
do
	local player = players["bufallo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 1333, 27, 27, 0 }
	end
end
do
	local player = players["apashee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 5809, 60, 72, 6779 }
			player[9][2][5] = { 5637, 53, 61, 6956 }
	end
end
do
	local player = players["bulldawg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 5724, 61, 73, 6680 }
	end
end
do
	local player = players["cowpiumx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][5] = { 7206, 33, 41, 8891 }
	end
end
do
	local player = players["tbread"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 5432, 84, 101, 7362 }
	end
end
do
	local player = players["apoma"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 4493, 114, 135, 6089 }
	end
end
do
	local player = players["blankname"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 5605, 77, 93, 7597 }
	end
end
do
	local player = players["saiyanek"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 6296, 54, 66, 8533 }
			player[9][2][4] = { 6107, 75, 87, 7971 }
			player[9][2][5] = { 6064, 67, 80, 7742 }
	end
end
do
	local player = players["snabel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][4] = { 5653, 80, 92, 7378 }
			player[9][2][5] = { 5771, 70, 85, 7368 }
	end
end
do
	local player = players["zz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 6257, 55, 67, 8481 }
			player[9][2][4] = { 3943, 85, 98, 5146 }
			player[9][2][5] = { 6814, 46, 54, 8700 }
			player[9][2][7] = { 6481, 35, 40, 6792 }
	end
end
do
	local player = players["senning"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 3529, 97, 111, 133 }
	end
end
do
	local player = players["holymakaroni"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 4765, 79, 90, 153 }
	end
end
do
	local player = players["seenidia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 2381, 113, 133, 113 }
	end
end
do
	local player = players["cocayfiesta"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 6882, 51, 54, 190 }
	end
end
do
	local player = players["kindled"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 1153, 142, 165, 76 }
			player[9][1][4] = { 3296, 65, 71, 108 }
			player[9][1][5] = { 5826, 59, 64, 174 }
	end
end
do
	local player = players["ppclittleman"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][5] = { 5459, 71, 77, 163 }
	end
end
do
	local player = players["tidetina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][5] = { 5554, 69, 74, 166 }
	end
end
do
	local player = players["berogodx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 4853, 72, 85, 2929 }
	end
end
do
	local player = players["dobro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][5] = { 6169, 46, 52, 3186 }
	end
end
do
	local player = players["zarelina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 7835, 22, 22, 3783 }
			player[9][2][5] = { 7361, 24, 26, 3802 }
	end
end
do
	local player = players["hexxana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 6023, 55, 64, 7508 }
	end
end
do
	local player = players["maccio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 6112, 49, 58, 7618 }
			player[9][3][5] = { 6053, 62, 70, 6181 }
	end
end
do
	local player = players["martes"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 4198, 43, 48, 108 }
	end
end
do
	local player = players["bigaria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 5909, 71, 80, 6881 }
			player[9][3][5] = { 6164, 56, 62, 6374 }
	end
end
do
	local player = players["cetica"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 3390, 94, 105, 3948 }
	end
end
do
	local player = players["udbash"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][9] = { 6993, 6, 7, 4658 }
	end
end
do
	local player = players["zizare"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 6020, 67, 77, 7943 }
			player[9][2][4] = { 8768, 19, 21, 10578 }
			player[9][2][5] = { 7593, 27, 32, 9747 }
	end
end
do
	local player = players["runan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][5] = { 2638, 18, 19, 2372 }
	end
end
do
	local player = players["chica"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][1] = { 762, 86, 98, 0 }
	end
end
do
	local player = players["algirka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][1] = { 6578, 40, 46, 9929 }
			player[9][1][5] = { 6704, 51, 55, 9169 }
	end
end
do
	local player = players["keikosnipes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 750, 109, 130, 1247 }
	end
end
do
	local player = players["csatakukacc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][4] = { 7553, 56, 64, 8949 }
			player[9][2][5] = { 6617, 58, 70, 8402 }
	end
end
do
	local player = players["fkksafari"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 8308, 20, 23, 11195 }
			player[9][2][5] = { 3017, 90, 107, 3831 }
	end
end
do
	local player = players["irishklng"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 2775, 108, 128, 4616 }
	end
end
do
	local player = players["pakisstan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 5557, 56, 69, 9242 }
	end
end
do
	local player = players["tejiiwar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][1] = { 5271, 73, 86, 8766 }
			player[9][2][5] = { 6547, 61, 73, 8314 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
