-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "togc"
local chunkStartIndex = 29849
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["szakszuka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2321, 797, 1920, 1891 }
	end
end
do
	local player = players["covidspred"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9316, 97, 172, 2630 }
	end
end
do
	local player = players["tobz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9684, 43, 80, 3726 }
	end
end
do
	local player = players["pintsized"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9252, 106, 188, 2599 }
	end
end
do
	local player = players["perkinqlo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4378, 614, 1406, 2040 }
	end
end
do
	local player = players["iunholy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9636, 48, 92, 3150 }
	end
end
do
	local player = players["edwa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1818, 367, 766, 2490 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5719, 692, 1434, 8901 }
	end
end
do
	local player = players["annabeth"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7727, 294, 569, 2304 }
	end
end
do
	local player = players["albacette"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1500, 885, 2207, 1753 }
	end
end
do
	local player = players["mendeku"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6579, 409, 856, 2202 }
	end
end
do
	local player = players["deathnyht"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9120, 125, 221, 2561 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4932, 956, 2057, 8107 }
	end
end
do
	local player = players["deffy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8455, 211, 387, 2401 }
	end
end
do
	local player = players["bylachka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9136, 121, 217, 2564 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8939, 64, 97, 10257 }
	end
end
do
	local player = players["hopereaper"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2277, 804, 1931, 1887 }
	end
end
do
	local player = players["wrongclick"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2517, 780, 1871, 1905 }
	end
end
do
	local player = players["keqqs"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9012, 141, 248, 2535 }
	end
end
do
	local player = players["faexd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5318, 529, 1171, 2108 }
	end
end
do
	local player = players["mightytauren"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8940, 151, 266, 2507 }
	end
end
do
	local player = players["noflames"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5762, 488, 1060, 2139 }
	end
end
do
	local player = players["conquerror"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6118, 452, 971, 2169 }
	end
end
do
	local player = players["greencavi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2745, 764, 1814, 1928 }
	end
end
do
	local player = players["asbitter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3729, 678, 1568, 1994 }
	end
end
do
	local player = players["sporayrdog"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6098, 454, 976, 2168 }
	end
end
do
	local player = players["pisofshiit"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3501, 702, 1625, 1976 }
	end
end
do
	local player = players["idontneedtot"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9024, 139, 245, 2537 }
	end
end
do
	local player = players["traurer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9384, 88, 155, 2654 }
	end
end
do
	local player = players["hakadk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8323, 226, 420, 2378 }
	end
end
do
	local player = players["uythir"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6812, 524, 1068, 9369 }
	end
end
do
	local player = players["classyc"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4334, 619, 1417, 2036 }
	end
end
do
	local player = players["tsinish"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8267, 227, 424, 2361 }
	end
end
do
	local player = players["noobpalafdk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4748, 297, 633, 6504 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4921, 961, 2073, 8089 }
	end
end
do
	local player = players["mustart"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5517, 243, 513, 7558 }
	end
end
do
	local player = players["eljean"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4786, 571, 1304, 2066 }
	end
end
do
	local player = players["ergonom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3335, 335, 713, 4569 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3692, 1338, 3087, 6068 }
	end
end
do
	local player = players["chadbro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4669, 301, 641, 6396 }
	end
end
do
	local player = players["whiplashed"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1672, 385, 794, 2290 }
	end
end
do
	local player = players["sanemii"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4397, 1171, 2640, 7227 }
	end
end
do
	local player = players["cusdamatto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4839, 997, 2184, 7953 }
	end
end
do
	local player = players["deathez"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4860, 986, 2149, 7989 }
	end
end
do
	local player = players["janpawulon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5303, 756, 1580, 8716 }
	end
end
do
	local player = players["foucaultt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8231, 309, 593, 10241 }
	end
end
do
	local player = players["zizise"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4514, 1121, 2528, 7420 }
	end
end
do
	local player = players["mitherno"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8993, 192, 338, 10871 }
	end
end
do
	local player = players["tiranoflan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4126, 639, 1469, 2020 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5183, 819, 1730, 8518 }
	end
end
do
	local player = players["vodkataranka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6253, 613, 1255, 9127 }
	end
end
do
	local player = players["plaguestone"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8414, 277, 532, 10386 }
	end
end
do
	local player = players["bestdream"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8981, 193, 342, 10866 }
	end
end
do
	local player = players["neddk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8393, 279, 539, 10369 }
	end
end
do
	local player = players["darknesrises"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2793, 760, 1802, 1931 }
	end
end
do
	local player = players["nubedk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5255, 782, 1639, 8637 }
	end
end
do
	local player = players["greenciaga"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5020, 918, 1961, 8251 }
	end
end
do
	local player = players["kopassdikej"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5000, 928, 1980, 8218 }
	end
end
do
	local player = players["dkarz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6731, 538, 1095, 9335 }
	end
end
do
	local player = players["umokora"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9376, 120, 210, 11262 }
	end
end
do
	local player = players["derazdk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6131, 631, 1296, 9062 }
	end
end
do
	local player = players["dreadkong"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6687, 397, 829, 2211 }
	end
end
do
	local player = players["killuv"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9229, 149, 259, 11071 }
	end
end
do
	local player = players["shamicox"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8996, 191, 337, 10873 }
	end
end
do
	local player = players["specific"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7481, 418, 844, 9724 }
	end
end
do
	local player = players["nemamruke"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5238, 538, 1191, 2102 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5031, 908, 1945, 8269 }
	end
end
do
	local player = players["wzm"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5647, 700, 1458, 8878 }
	end
end
do
	local player = players["litxy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9405, 115, 200, 11314 }
	end
end
do
	local player = players["lemanski"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6860, 758, 1455, 9514 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2070, 181, 340, 2 }
	end
end
do
	local player = players["hornychick"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6683, 801, 1537, 9401 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9952, 3, 3, 533 }
	end
end
do
	local player = players["francescagna"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8849, 329, 534, 10897 }
	end
end
do
	local player = players["budokaii"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9281, 207, 327, 11396 }
	end
end
do
	local player = players["camdru"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4007, 1759, 3761, 6889 }
	end
end
do
	local player = players["tumanq"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5507, 103, 202, 18 }
	end
end
do
	local player = players["leerki"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4366, 1579, 3297, 7505 }
	end
end
do
	local player = players["mercedez"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5502, 1057, 2084, 8808 }
	end
end
do
	local player = players["equal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7269, 63, 117, 56 }
	end
end
do
	local player = players["holyclaws"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8510, 418, 691, 10614 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2819, 164, 309, 3 }
	end
end
do
	local player = players["phydrax"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7899, 556, 974, 10179 }
	end
end
do
	local player = players["spiderdudu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4762, 1448, 2919, 7633 }
	end
end
do
	local player = players["kimboo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4676, 1364, 2792, 8038 }
	end
end
do
	local player = players["raazia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6629, 814, 1562, 9370 }
	end
end
do
	local player = players["hirowla"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4856, 1232, 2492, 8347 }
	end
end
do
	local player = players["tiupateta"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7253, 675, 1273, 9772 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 1079, 205, 373, 1 }
	end
end
do
	local player = players["pluf"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9007, 291, 461, 11048 }
	end
end
do
	local player = players["rexbestsex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8527, 415, 683, 10633 }
	end
end
do
	local player = players["boomo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7966, 544, 943, 10236 }
	end
end
do
	local player = players["abitou"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7191, 685, 1302, 9717 }
	end
end
do
	local player = players["sarayu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5991, 92, 171, 29 }
	end
end
do
	local player = players["naturekohza"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9076, 271, 429, 11094 }
	end
end
do
	local player = players["helkat"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6878, 753, 1447, 9524 }
	end
end
do
	local player = players["peekabubu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4986, 1169, 2323, 8510 }
	end
end
do
	local player = players["winlife"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6519, 834, 1613, 9307 }
	end
end
do
	local player = players["zelepuga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9225, 228, 360, 11294 }
	end
end
do
	local player = players["biblos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6450, 851, 1645, 9263 }
	end
end
do
	local player = players["droouid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8495, 422, 698, 10604 }
	end
end
do
	local player = players["paxle"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5468, 1068, 2100, 8792 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4053, 136, 258, 7 }
	end
end
do
	local player = players["necrolity"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3207, 1989, 4387, 5514 }
	end
end
do
	local player = players["koalushka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7487, 628, 1165, 9909 }
	end
end
do
	local player = players["mously"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4771, 1299, 2642, 8202 }
	end
end
do
	local player = players["healthyfood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7199, 683, 1298, 9719 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8489, 39, 64, 97 }
	end
end
do
	local player = players["boibakukang"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8892, 318, 514, 10952 }
	end
end
do
	local player = players["notienescure"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3921, 1797, 3861, 6740 }
	end
end
do
	local player = players["ervaverdinha"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5256, 1109, 2198, 8675 }
	end
end
do
	local player = players["gkioumis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3820, 1833, 3976, 6567 }
	end
end
do
	local player = players["norvay"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4263, 1641, 3450, 7328 }
	end
end
do
	local player = players["bentomon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5923, 964, 1889, 9015 }
	end
end
do
	local player = players["srunezametno"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6283, 86, 156, 37 }
	end
end
do
	local player = players["bobrdrurwa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7813, 573, 1014, 10120 }
	end
end
do
	local player = players["lindaw"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5660, 1023, 2011, 8874 }
	end
end
do
	local player = players["eriochrome"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4398, 1553, 3234, 7561 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2026, 182, 341, 2 }
	end
end
do
	local player = players["costelagorda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6559, 819, 1562, 9313 }
	end
end
do
	local player = players["paciellodrui"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8223, 492, 824, 10407 }
	end
end
do
	local player = players["restomam"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4158, 1701, 3591, 7148 }
	end
end
do
	local player = players["luzlunar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7838, 569, 1002, 10136 }
	end
end
do
	local player = players["mahkah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7031, 718, 1376, 9625 }
	end
end
do
	local player = players["bubolina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5884, 515, 1076, 9935 }
	end
end
do
	local player = players["vodonos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4626, 894, 2053, 8153 }
	end
end
do
	local player = players["ghostga"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6577, 431, 895, 10251 }
	end
end
do
	local player = players["nybo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9721, 46, 74, 12542 }
	end
end
do
	local player = players["crnamaca"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5489, 590, 1251, 9674 }
	end
end
do
	local player = players["kopasscat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4675, 878, 2015, 8240 }
	end
end
do
	local player = players["windance"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5111, 719, 1621, 9009 }
	end
end
do
	local player = players["cryptocat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7286, 351, 710, 10587 }
	end
end
do
	local player = players["powlo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4320, 929, 2116, 7474 }
	end
end
do
	local player = players["nyansei"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8855, 175, 300, 11411 }
	end
end
do
	local player = players["lycane"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4810, 838, 1926, 8478 }
	end
end
do
	local player = players["tullrian"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5104, 724, 1635, 8996 }
	end
end
do
	local player = players["calabacin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7054, 692, 1278, 9558 }
	end
end
do
	local player = players["fluffyk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5348, 639, 1399, 9426 }
	end
end
do
	local player = players["zverina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6753, 412, 849, 10332 }
	end
end
do
	local player = players["anicrb"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5716, 534, 1120, 9882 }
	end
end
do
	local player = players["taylbakyc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8530, 223, 385, 11159 }
	end
end
do
	local player = players["lameheart"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4982, 766, 1717, 8781 }
	end
end
do
	local player = players["nightvizion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9433, 94, 142, 12015 }
	end
end
do
	local player = players["limagood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4595, 1414, 2926, 7899 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9051, 148, 249, 11592 }
	end
end
do
	local player = players["nesqquik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6945, 384, 784, 10413 }
	end
end
do
	local player = players["mightydruid"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6160, 469, 956, 10029 }
	end
end
do
	local player = players["fangmera"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7401, 636, 1168, 9827 }
	end
end
do
	local player = players["velvetlust"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5109, 709, 1587, 9004 }
	end
end
do
	local player = players["jamby"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4798, 816, 1850, 8452 }
	end
end
do
	local player = players["jeckiechan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6255, 462, 942, 10074 }
	end
end
do
	local player = players["ayecantdie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4873, 809, 1833, 8431 }
	end
end
do
	local player = players["mystercio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2203, 178, 331, 2 }
	end
end
do
	local player = players["drulio"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3855, 1821, 3945, 6626 }
	end
end
do
	local player = players["taheo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4714, 121, 233, 11 }
	end
end
do
	local player = players["wtfisaimshot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5900, 964, 2136, 8397 }
	end
end
do
	local player = players["tusknar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4488, 1250, 2871, 7708 }
	end
end
do
	local player = players["tym"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3932, 1427, 3324, 7032 }
	end
end
do
	local player = players["goodhuntt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3583, 1702, 4081, 6408 }
	end
end
do
	local player = players["missbasic"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7607, 599, 1247, 9361 }
	end
end
do
	local player = players["medhaf"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6356, 43, 97, 8559 }
	end
end
do
	local player = players["tamingg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3705, 1634, 3907, 6626 }
	end
end
do
	local player = players["fujiyama"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7993, 503, 1046, 9621 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4655, 66, 167, 6268 }
	end
end
do
	local player = players["wardanhunter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6981, 744, 1573, 9007 }
	end
end
do
	local player = players["mothly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8752, 329, 651, 10191 }
	end
end
do
	local player = players["toodi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5429, 57, 135, 7311 }
	end
end
do
	local player = players["ymion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7123, 711, 1499, 9082 }
	end
end
do
	local player = players["makealizard"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2948, 1943, 4797, 5272 }
	end
end
do
	local player = players["heragon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4205, 304, 639, 5760 }
	end
end
do
	local player = players["zipmaga"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5837, 738, 1408, 10392 }
	end
end
do
	local player = players["shazeb"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9479, 112, 177, 13016 }
	end
end
do
	local player = players["pyroholick"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5448, 790, 1495, 10163 }
	end
end
do
	local player = players["paciellomage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9166, 169, 283, 12613 }
	end
end
do
	local player = players["greatshock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6151, 691, 1302, 10568 }
	end
end
do
	local player = players["rokkiiee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2809, 1573, 3206, 6165 }
	end
end
do
	local player = players["jumpz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3990, 1181, 2287, 8757 }
	end
end
do
	local player = players["rastafirean"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4309, 1023, 2025, 9458 }
	end
end
do
	local player = players["fawly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3817, 1316, 2643, 8377 }
	end
end
do
	local player = players["abeckette"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6322, 662, 1244, 10661 }
	end
end
do
	local player = players["defunctmage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5592, 781, 1491, 10265 }
	end
end
do
	local player = players["holyyflame"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3211, 1516, 3065, 7048 }
	end
end
do
	local player = players["maestrro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2646, 1597, 3253, 5807 }
	end
end
do
	local player = players["klarinda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5030, 880, 1715, 167 }
	end
end
do
	local player = players["travery"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9037, 218, 333, 267 }
	end
end
do
	local player = players["ophiler"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7608, 483, 826, 219 }
	end
end
do
	local player = players["mesi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1548, 1332, 2916, 103 }
	end
end
do
	local player = players["solarian"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7251, 535, 949, 210 }
	end
end
do
	local player = players["buggysama"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2731, 1193, 2508, 127 }
	end
end
do
	local player = players["bestholypal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5512, 811, 1549, 176 }
	end
end
do
	local player = players["ahrixa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 939, 1424, 3216, 77 }
	end
end
do
	local player = players["selyse"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2157, 1260, 2706, 117 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3325, 1125, 3185, 1016 }
	end
end
do
	local player = players["wolfish"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6614, 632, 1169, 197 }
	end
end
do
	local player = players["roidelaforai"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6274, 687, 1286, 190 }
	end
end
do
	local player = players["notshameqt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4636, 1395, 2917, 8364 }
	end
end
do
	local player = players["jelenarozga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9455, 130, 189, 299 }
	end
end
do
	local player = players["plasticworld"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8170, 384, 632, 235 }
	end
end
do
	local player = players["halki"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6782, 858, 1670, 9487 }
	end
end
do
	local player = players["soullighter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4349, 976, 1950, 156 }
	end
end
do
	local player = players["prvovencani"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9235, 175, 265, 281 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1260, 1419, 4170, 516 }
	end
end
do
	local player = players["mentais"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6722, 599, 1095, 199 }
	end
end
do
	local player = players["lunadelalba"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3990, 1017, 2074, 151 }
	end
end
do
	local player = players["shmarapvl"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8805, 267, 413, 258 }
	end
end
do
	local player = players["xxqsgg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6930, 579, 1060, 203 }
	end
end
do
	local player = players["sshaka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4856, 909, 1775, 164 }
	end
end
do
	local player = players["chupka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 1217, 2311, 5157, 2196 }
	end
end
do
	local player = players["inngili"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8305, 492, 880, 10381 }
	end
end
do
	local player = players["salesforce"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8055, 398, 672, 231 }
	end
end
do
	local player = players["gonepala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3592, 1075, 2211, 143 }
	end
end
do
	local player = players["ilargi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8429, 339, 543, 242 }
	end
end
do
	local player = players["budzogan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9790, 45, 101, 4362 }
	end
end
do
	local player = players["fiutel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2212, 1291, 3716, 716 }
	end
end
do
	local player = players["xutinpui"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7319, 520, 1280, 2760 }
	end
end
do
	local player = players["lash"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8530, 300, 702, 3207 }
	end
end
do
	local player = players["runduck"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1277, 1415, 4162, 521 }
	end
end
do
	local player = players["uhyie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 413, 1523, 4574, 296 }
	end
end
do
	local player = players["mahhalrahm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5717, 768, 2044, 2255 }
	end
end
do
	local player = players["yaatora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 537, 1503, 4515, 337 }
	end
end
do
	local player = players["unobpaladin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7281, 528, 1298, 2746 }
	end
end
do
	local player = players["xloty"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7214, 762, 1446, 9725 }
	end
end
do
	local player = players["zapatico"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3298, 1132, 3198, 1010 }
	end
end
do
	local player = players["salvalixeira"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5323, 839, 1614, 173 }
	end
end
do
	local player = players["homester"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3556, 1095, 3075, 1094 }
	end
end
do
	local player = players["resiste"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3667, 1074, 3022, 1145 }
	end
end
do
	local player = players["saery"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6953, 574, 1052, 203 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9218, 167, 374, 3616 }
	end
end
do
	local player = players["ioltrash"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7228, 538, 957, 209 }
	end
end
do
	local player = players["junktrunk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7518, 497, 857, 217 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3388, 1119, 3155, 1042 }
	end
end
do
	local player = players["bradas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5761, 758, 2023, 2269 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4913, 1273, 2639, 8604 }
	end
end
do
	local player = players["fatherofwow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5589, 783, 2105, 2207 }
	end
end
do
	local player = players["chichadraza"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5080, 860, 2348, 2008 }
	end
end
do
	local player = players["nouchie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5247, 830, 2268, 2073 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4209, 1771, 3766, 7594 }
	end
end
do
	local player = players["wloskarobota"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2497, 1257, 3580, 776 }
	end
end
do
	local player = players["puremed"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3178, 1133, 2354, 135 }
	end
end
do
	local player = players["lyghtnyng"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7117, 788, 1496, 9671 }
	end
end
do
	local player = players["shadowmourn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2920, 1197, 3378, 896 }
	end
end
do
	local player = players["lightstrings"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5585, 784, 2107, 2206 }
	end
end
do
	local player = players["solahdepapel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6849, 598, 1504, 2612 }
	end
end
do
	local player = players["polazia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9023, 209, 467, 3490 }
	end
end
do
	local player = players["nncurse"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8764, 362, 642, 10739 }
	end
end
do
	local player = players["cappuccinoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6964, 582, 1449, 2648 }
	end
end
do
	local player = players["palarenger"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2618, 1204, 2547, 125 }
	end
end
do
	local player = players["torches"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4321, 1684, 3563, 7796 }
	end
end
do
	local player = players["noobpala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2230, 1248, 2681, 119 }
	end
end
do
	local player = players["frizk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2589, 1209, 2557, 125 }
	end
end
do
	local player = players["bikiniporn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5665, 1108, 2249, 8962 }
	end
end
do
	local player = players["thingyanma"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4390, 1620, 3425, 7920 }
	end
end
do
	local player = players["prescelto"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9350, 135, 311, 3704 }
	end
end
do
	local player = players["takamusha"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9495, 152, 263, 11731 }
	end
end
do
	local player = players["hoper"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5733, 1095, 2214, 9001 }
	end
end
do
	local player = players["sindor"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4310, 1698, 3588, 7776 }
	end
end
do
	local player = players["allizhon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8673, 388, 689, 10669 }
	end
end
do
	local player = players["loveandtrust"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4455, 1564, 3289, 8038 }
	end
end
do
	local player = players["ivkztwo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6059, 715, 1881, 2357 }
	end
end
do
	local player = players["bubsy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4521, 1503, 3156, 8157 }
	end
end
do
	local player = players["prommise"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7640, 660, 1225, 9958 }
	end
end
do
	local player = players["iyat"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4013, 1900, 4098, 7241 }
	end
end
do
	local player = players["shredy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5511, 1145, 2329, 8887 }
	end
end
do
	local player = players["cirka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9601, 123, 208, 11990 }
	end
end
do
	local player = players["itselrow"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9360, 187, 333, 11517 }
	end
end
do
	local player = players["draeniana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9132, 253, 451, 11166 }
	end
end
do
	local player = players["antishokp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9254, 156, 357, 3638 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7626, 664, 1232, 9949 }
	end
end
do
	local player = players["nethark"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9290, 162, 246, 285 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9784, 63, 113, 12608 }
	end
end
do
	local player = players["levtigar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9828, 51, 90, 12865 }
	end
end
do
	local player = players["unterwelt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7709, 463, 791, 221 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6427, 945, 1854, 9324 }
	end
end
do
	local player = players["gasayyuno"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3908, 1032, 2102, 149 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5050, 1244, 2568, 8671 }
	end
end
do
	local player = players["shishider"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4311, 983, 1963, 155 }
	end
end
do
	local player = players["habibioss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7828, 436, 1037, 2928 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9699, 91, 157, 12201 }
	end
end
do
	local player = players["holyzor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3878, 1031, 2921, 1257 }
	end
end
do
	local player = players["gobblepwnz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9325, 198, 351, 11465 }
	end
end
do
	local player = players["danimo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9520, 111, 230, 3841 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9541, 139, 239, 11859 }
	end
end
do
	local player = players["luthina"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4352, 1653, 3503, 7852 }
	end
end
do
	local player = players["mowaj"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 456, 1440, 3226, 37 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4520, 1431, 2941, 8156 }
	end
end
do
	local player = players["asiimir"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3382, 2162, 4776, 6102 }
	end
end
do
	local player = players["damvroto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9966, 12, 18, 14458 }
	end
end
do
	local player = players["bagoly"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4162, 1768, 3748, 7509 }
	end
end
do
	local player = players["wanwala"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5320, 1195, 2428, 8800 }
	end
end
do
	local player = players["abljo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7883, 601, 1099, 10107 }
	end
end
do
	local player = players["pepcci"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 306, 2318, 5169, 552 }
	end
end
do
	local player = players["bishopr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9252, 223, 389, 11361 }
	end
end
do
	local player = players["ralyy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7962, 581, 1058, 10166 }
	end
end
do
	local player = players["valyrio"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6486, 919, 1787, 9329 }
	end
end
do
	local player = players["hassyy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7068, 330, 542, 143 }
	end
end
do
	local player = players["rimskix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3588, 662, 1184, 108 }
	end
end
do
	local player = players["druzlok"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6466, 389, 653, 136 }
	end
end
do
	local player = players["tonyfaith"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8076, 224, 356, 162 }
	end
end
do
	local player = players["kekerek"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3978, 632, 1112, 113 }
	end
end
do
	local player = players["demostater"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7409, 299, 479, 147 }
	end
end
do
	local player = players["powerwordhug"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6813, 356, 589, 140 }
	end
end
do
	local player = players["askyourmom"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2856, 724, 1319, 98 }
	end
end
do
	local player = players["oldlady"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4578, 34, 46, 117 }
	end
end
do
	local player = players["healex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2206, 779, 1439, 83 }
	end
end
do
	local player = players["dreamfull"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5518, 481, 828, 127 }
	end
end
do
	local player = players["vandralis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1902, 803, 1495, 72 }
	end
end
do
	local player = players["xillion"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6423, 395, 661, 135 }
	end
end
do
	local player = players["gustevon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5542, 29, 38, 134 }
	end
end
do
	local player = players["angelicdust"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5561, 476, 820, 127 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7590, 15, 21, 170 }
	end
end
do
	local player = players["zaku"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 482, 49, 80, 2 }
	end
end
do
	local player = players["urols"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4921, 542, 938, 122 }
	end
end
do
	local player = players["nadx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2201, 780, 1440, 83 }
	end
end
do
	local player = players["pizi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6959, 341, 562, 142 }
	end
end
do
	local player = players["bananatheist"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7285, 313, 502, 145 }
	end
end
do
	local player = players["hwinoree"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3382, 678, 1222, 105 }
	end
end
do
	local player = players["sacerman"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4891, 1087, 2281, 8705 }
	end
end
do
	local player = players["restodruid"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6265, 25, 32, 139 }
	end
end
do
	local player = players["darkdeathvxv"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4188, 1533, 3310, 7570 }
	end
end
do
	local player = players["yoshiisan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4583, 1277, 2669, 8284 }
	end
end
do
	local player = players["overfarm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4699, 33, 45, 118 }
	end
end
do
	local player = players["tergo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6751, 721, 1451, 9695 }
	end
end
do
	local player = players["neyto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7759, 487, 1001, 10338 }
	end
end
do
	local player = players["wiktoria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3747, 1747, 3886, 6773 }
	end
end
do
	local player = players["karuxlag"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9585, 83, 190, 12399 }
	end
end
do
	local player = players["xeah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8830, 252, 523, 11251 }
	end
end
do
	local player = players["nagamasa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5663, 28, 37, 135 }
	end
end
do
	local player = players["jink"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4086, 1598, 3489, 7386 }
	end
end
do
	local player = players["yoshiisama"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6337, 810, 1636, 9452 }
	end
end
do
	local player = players["unibrow"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4586, 1273, 2662, 8290 }
	end
end
do
	local player = players["demonry"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4194, 1527, 3295, 7581 }
	end
end
do
	local player = players["orela"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4701, 1178, 2470, 8497 }
	end
end
do
	local player = players["seraphimtrol"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 667, 882, 1723, 9 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8072, 12, 17, 190 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9196, 173, 360, 11717 }
	end
end
do
	local player = players["speedstyle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4728, 1154, 2416, 8547 }
	end
end
do
	local player = players["cosmos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8806, 258, 534, 11235 }
	end
end
do
	local player = players["atomnik"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9140, 182, 385, 11626 }
	end
end
do
	local player = players["darkmelter"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8546, 314, 650, 10948 }
	end
end
do
	local player = players["lynaria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4822, 1104, 2312, 8674 }
	end
end
do
	local player = players["shadowrod"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3960, 1664, 3663, 7159 }
	end
end
do
	local player = players["proglas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4212, 1513, 3264, 7613 }
	end
end
do
	local player = players["tifani"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4209, 1516, 3270, 7609 }
	end
end
do
	local player = players["kolaicho"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4103, 1587, 3461, 7416 }
	end
end
do
	local player = players["alypriest"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4544, 1303, 2730, 8214 }
	end
end
do
	local player = players["xerciez"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4448, 1366, 2893, 8040 }
	end
end
do
	local player = players["asenrpriest"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3417, 1858, 4163, 6177 }
	end
end
do
	local player = players["zerabott"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6603, 754, 1517, 9596 }
	end
end
do
	local player = players["kopele"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4211, 1514, 3267, 7612 }
	end
end
do
	local player = players["wodecki"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2222, 776, 1436, 83 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4232, 1506, 3238, 7649 }
	end
end
do
	local player = players["lostshade"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4044, 1623, 3553, 7309 }
	end
end
do
	local player = players["puntizela"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5443, 978, 2035, 8990 }
	end
end
do
	local player = players["lilywatt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4855, 1097, 2297, 8695 }
	end
end
do
	local player = players["icsi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9626, 76, 168, 12459 }
	end
end
do
	local player = players["tlana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1014, 863, 1659, 24 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6518, 777, 1555, 9558 }
	end
end
do
	local player = players["sinuhe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8082, 421, 857, 10580 }
	end
end
do
	local player = players["aurastrasza"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3462, 1842, 4122, 6258 }
	end
end
do
	local player = players["dywa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6269, 822, 1666, 9416 }
	end
end
do
	local player = players["topooc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5042, 1166, 2645, 9206 }
	end
end
do
	local player = players["blinkoneitwo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5803, 1003, 2239, 9509 }
	end
end
do
	local player = players["icky"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4369, 1555, 3681, 8388 }
	end
end
do
	local player = players["darkjinn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3057, 2069, 5129, 5870 }
	end
end
do
	local player = players["itricksteri"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8245, 441, 933, 10645 }
	end
end
do
	local player = players["homevideo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9659, 96, 183, 12149 }
	end
end
do
	local player = players["sinclaire"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9381, 160, 331, 11624 }
	end
end
do
	local player = players["mahouniche"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9284, 180, 383, 11509 }
	end
end
do
	local player = players["koxxq"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5299, 1108, 2508, 9313 }
	end
end
do
	local player = players["delico"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4782, 1215, 2784, 9087 }
	end
end
do
	local player = players["raynox"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7885, 507, 1069, 10398 }
	end
end
do
	local player = players["mcamper"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6499, 836, 1868, 9780 }
	end
end
do
	local player = players["ginsengstrip"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6169, 920, 2044, 9646 }
	end
end
do
	local player = players["foxxystab"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4843, 1203, 2751, 9105 }
	end
end
do
	local player = players["supnikk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9527, 124, 253, 11863 }
	end
end
do
	local player = players["ghostrabbita"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5104, 1150, 2612, 9224 }
	end
end
do
	local player = players["livrim"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4644, 1295, 2994, 8915 }
	end
end
do
	local player = players["faddria"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7834, 537, 1156, 10417 }
	end
end
do
	local player = players["kryss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4660, 1280, 2960, 8947 }
	end
end
do
	local player = players["thedarkhero"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4630, 1305, 3030, 8888 }
	end
end
do
	local player = players["bauhaw"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4249, 1804, 4317, 7315 }
	end
end
do
	local player = players["iabuba"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3975, 1788, 4374, 7630 }
	end
end
do
	local player = players["nickga"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5888, 980, 2194, 9540 }
	end
end
do
	local player = players["jebane"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3248, 2037, 5050, 6236 }
	end
end
do
	local player = players["petroula"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4128, 55, 117, 5331 }
	end
end
do
	local player = players["xtremepower"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3515, 435, 822, 18 }
	end
end
do
	local player = players["misogeshammy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3801, 117, 229, 5788 }
	end
end
do
	local player = players["wurstii"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 466, 610, 1207, 0 }
	end
end
do
	local player = players["hallogenka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 363, 617, 1221, 0 }
	end
end
do
	local player = players["medisinmadur"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4186, 397, 737, 25 }
	end
end
do
	local player = players["flashcast"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5979, 286, 510, 45 }
	end
end
do
	local player = players["drogobert"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2620, 465, 880, 10 }
	end
end
do
	local player = players["ogino"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4930, 90, 185, 7508 }
	end
end
do
	local player = players["dephxanter"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4333, 382, 706, 26 }
	end
end
do
	local player = players["cherniymag"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4128, 1138, 2282, 6931 }
	end
end
do
	local player = players["amelianka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6421, 90, 190, 10474 }
	end
end
do
	local player = players["hidralizco"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4001, 1118, 2224, 6718 }
	end
end
do
	local player = players["brithany"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6080, 540, 986, 9024 }
	end
end
do
	local player = players["soulslacker"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5007, 750, 1392, 8406 }
	end
end
do
	local player = players["wegg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6533, 497, 924, 9282 }
	end
end
do
	local player = players["drinkerwow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5718, 609, 1141, 8914 }
	end
end
do
	local player = players["caidie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3875, 1190, 2413, 6507 }
	end
end
do
	local player = players["imppale"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5002, 782, 1475, 8398 }
	end
end
do
	local player = players["mortticia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4352, 1071, 2130, 7307 }
	end
end
do
	local player = players["mestredeobra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9230, 115, 206, 11024 }
	end
end
do
	local player = players["lockako"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4742, 916, 1763, 7962 }
	end
end
do
	local player = players["toxictrait"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5943, 578, 1081, 9011 }
	end
end
do
	local player = players["lockchey"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6165, 545, 1022, 9099 }
	end
end
do
	local player = players["panzerkampfs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5515, 641, 1195, 8819 }
	end
end
do
	local player = players["wellandor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4671, 950, 1842, 7842 }
	end
end
do
	local player = players["helso"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4970, 798, 1507, 8345 }
	end
end
do
	local player = players["atmossfear"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4965, 186, 415, 8099 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4770, 905, 1736, 8008 }
	end
end
do
	local player = players["lovemebabe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6375, 518, 966, 9198 }
	end
end
do
	local player = players["yasmim"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5086, 730, 1370, 8540 }
	end
end
do
	local player = players["zeroiine"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3165, 1264, 2580, 5315 }
	end
end
do
	local player = players["brujas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5058, 748, 1401, 8493 }
	end
end
do
	local player = players["demonessa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4887, 838, 1602, 8205 }
	end
end
do
	local player = players["neigefashi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4986, 788, 1486, 8371 }
	end
end
do
	local player = players["absoluteape"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4139, 1133, 2274, 6950 }
	end
end
do
	local player = players["koldynka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4949, 807, 1534, 8309 }
	end
end
do
	local player = players["sumonna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4132, 1136, 2279, 6938 }
	end
end
do
	local player = players["jiperscripex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6607, 1318, 3004, 11298 }
	end
end
do
	local player = players["okun"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6827, 1244, 2809, 11437 }
	end
end
do
	local player = players["wildbor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3839, 2252, 5613, 9688 }
	end
end
do
	local player = players["rezk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7497, 1016, 2216, 11889 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4481, 65, 171, 948 }
	end
end
do
	local player = players["sharila"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6820, 1247, 2816, 11434 }
	end
end
do
	local player = players["kilerix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5103, 1814, 4335, 10450 }
	end
end
do
	local player = players["pyszczku"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3357, 2781, 7299, 8471 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3766, 76, 193, 608 }
	end
end
do
	local player = players["exxecute"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7684, 944, 2051, 12025 }
	end
end
do
	local player = players["prextwar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2939, 3024, 8191, 7416 }
	end
end
do
	local player = players["stalevsetko"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5770, 1597, 3745, 10821 }
	end
end
do
	local player = players["thedeed"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2505, 3159, 8590, 6322 }
	end
end
do
	local player = players["smackems"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9586, 230, 367, 14253 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6762, 35, 116, 2295 }
	end
end
do
	local player = players["lookatmyass"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3391, 2755, 7193, 8557 }
	end
end
do
	local player = players["chargebsha"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7661, 954, 2071, 12005 }
	end
end
do
	local player = players["smr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3865, 2213, 5487, 9754 }
	end
end
do
	local player = players["rockworm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6544, 1339, 3060, 11257 }
	end
end
do
	local player = players["anjosupremo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7467, 1026, 2243, 11867 }
	end
end
do
	local player = players["balmino"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5127, 1805, 4314, 10465 }
	end
end
do
	local player = players["youxiazs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7568, 993, 2154, 11933 }
	end
end
do
	local player = players["ivaanns"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3371, 2772, 7252, 8506 }
	end
end
do
	local player = players["zatypok"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4366, 2047, 4988, 10064 }
	end
end
do
	local player = players["kalrog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3843, 2249, 5595, 9698 }
	end
end
do
	local player = players["rayish"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3379, 2766, 7230, 8527 }
	end
end
do
	local player = players["asurac"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3462, 2677, 6956, 8737 }
	end
end
do
	local player = players["asteriks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5816, 1581, 3704, 10844 }
	end
end
do
	local player = players["zoomerbae"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2853, 3063, 8300, 7200 }
	end
end
do
	local player = players["smasch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9049, 466, 843, 13320 }
	end
end
do
	local player = players["krepps"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4027, 2142, 5288, 9882 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4123, 71, 182, 723 }
	end
end
do
	local player = players["alehteir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4672, 1948, 4717, 10231 }
	end
end
do
	local player = players["swadinger"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5004, 1849, 4423, 10396 }
	end
end
do
	local player = players["elheej"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3306, 2816, 7441, 8344 }
	end
end
do
	local player = players["rainingman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3207, 2882, 7677, 8092 }
	end
end
do
	local player = players["robbaz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2831, 3076, 8334, 7145 }
	end
end
do
	local player = players["cleaveslain"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2949, 3019, 8176, 7441 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
