-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "ulduar"
local chunkStartIndex = 10511
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["bangaranga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6489, 87, 218, 1679 }
	end
end
do
	local player = players["toraso"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6098, 278, 1122, 5653 }
	end
end
do
	local player = players["bdkqt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5911, 269, 892, 5267 }
	end
end
do
	local player = players["wiinters"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6356, 251, 822, 5664 }
	end
end
do
	local player = players["perception"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7398, 159, 512, 6593 }
	end
end
do
	local player = players["aquamari"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5992, 268, 884, 5340 }
	end
end
do
	local player = players["elopper"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5595, 279, 927, 4986 }
	end
end
do
	local player = players["victorina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5553, 280, 936, 4949 }
	end
end
do
	local player = players["sujirukimide"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5827, 273, 903, 5193 }
	end
end
do
	local player = players["biggle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5428, 285, 953, 4837 }
	end
end
do
	local player = players["legynd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7346, 68, 165, 1778 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 8171, 89, 220, 7281 }
	end
end
do
	local player = players["frostfirst"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4638, 218, 633, 4133 }
	end
end
do
	local player = players["shednaros"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6053, 266, 879, 5394 }
	end
end
do
	local player = players["necrothy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7565, 140, 447, 6741 }
	end
end
do
	local player = players["litmon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6594, 229, 769, 5876 }
	end
end
do
	local player = players["pandorie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6329, 254, 831, 5640 }
	end
end
do
	local player = players["donverga"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4275, 269, 992, 3963 }
	end
end
do
	local player = players["abooat"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5540, 295, 1230, 5135 }
	end
end
do
	local player = players["vorpalbunnix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5405, 282, 1127, 5010 }
	end
end
do
	local player = players["wboggs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4719, 236, 835, 4424 }
	end
end
do
	local player = players["goldiggerr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6634, 238, 910, 6150 }
	end
end
do
	local player = players["immortanjoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6314, 236, 737, 5626 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6314, 236, 737, 5626 }
	end
end
do
	local player = players["antigen"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6255, 269, 1073, 5798 }
	end
end
do
	local player = players["crimsonaxe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3974, 241, 855, 3725 }
	end
end
do
	local player = players["toomas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4177, 295, 1199, 3872 }
	end
end
do
	local player = players["mercurian"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6394, 258, 1016, 5927 }
	end
end
do
	local player = players["passadena"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6466, 248, 977, 5995 }
	end
end
do
	local player = players["gotrekt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6325, 265, 1046, 5864 }
	end
end
do
	local player = players["areuwinning"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6864, 205, 687, 6117 }
	end
end
do
	local player = players["ohhoui"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6398, 257, 1013, 5931 }
	end
end
do
	local player = players["faelios"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7005, 201, 713, 6494 }
	end
end
do
	local player = players["fakeniwi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5584, 294, 1226, 5176 }
	end
end
do
	local player = players["antibustin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7673, 113, 355, 7113 }
	end
end
do
	local player = players["aokeeper"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6518, 237, 788, 5809 }
	end
end
do
	local player = players["oztheradlad"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5143, 304, 1280, 4768 }
	end
end
do
	local player = players["coils"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5109, 306, 1283, 4736 }
	end
end
do
	local player = players["pygmyteufel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1552, 151, 534, 1206 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 1552, 151, 534, 1206 }
	end
end
do
	local player = players["devan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7739, 105, 319, 7175 }
	end
end
do
	local player = players["charm"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5607, 286, 957, 4712 }
	end
end
do
	local player = players["kaynor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9385, 23, 34, 4 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 9385, 23, 34, 4 }
	end
end
do
	local player = players["busconovia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4106, 391, 1522, 3451 }
	end
end
do
	local player = players["dybbedudu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7272, 138, 467, 5720 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6816, 84, 172, 0 }
	end
end
do
	local player = players["vreemdeling"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5349, 329, 1186, 4495 }
	end
end
do
	local player = players["mushugato"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6944, 158, 523, 5614 }
	end
end
do
	local player = players["evadanger"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4622, 378, 1430, 3884 }
	end
end
do
	local player = players["yagi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2647, 421, 1657, 2224 }
	end
end
do
	local player = players["balenciganka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4716, 375, 1409, 3963 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7896, 65, 114, 0 }
	end
end
do
	local player = players["plafar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5715, 287, 1009, 4802 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8063, 62, 105, 0 }
	end
end
do
	local player = players["mirzoni"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5864, 266, 927, 4928 }
	end
end
do
	local player = players["dpykyp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5741, 284, 992, 4825 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3799, 132, 334, 0 }
	end
end
do
	local player = players["fajbyk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4884, 295, 855, 4105 }
	end
end
do
	local player = players["anuddernip"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6079, 235, 815, 5109 }
	end
end
do
	local player = players["aiorosh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5980, 246, 863, 5026 }
	end
end
do
	local player = players["astralpaw"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5486, 315, 1128, 4610 }
	end
end
do
	local player = players["chymio"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6751, 167, 556, 5562 }
	end
end
do
	local player = players["vacardix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7968, 114, 348, 5949 }
	end
end
do
	local player = players["druranja"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6032, 243, 840, 5069 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7952, 63, 111, 0 }
	end
end
do
	local player = players["barkinsons"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2197, 158, 420, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2197, 158, 420, 0 }
	end
end
do
	local player = players["daisi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2961, 144, 379, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2961, 144, 379, 0 }
	end
end
do
	local player = players["zatana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6313, 89, 199, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6313, 89, 199, 0 }
	end
end
do
	local player = players["supercreek"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6872, 83, 169, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6872, 83, 169, 0 }
	end
end
do
	local player = players["zugardady"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7318, 77, 145, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7318, 77, 145, 0 }
	end
end
do
	local player = players["eliazdruid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4395, 122, 302, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4395, 122, 302, 0 }
	end
end
do
	local player = players["treeyedraven"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4581, 116, 292, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4581, 116, 292, 0 }
	end
end
do
	local player = players["nolgorn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 8641, 47, 74, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8641, 47, 74, 0 }
	end
end
do
	local player = players["deanosmkii"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 3818, 131, 333, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3818, 131, 333, 0 }
	end
end
do
	local player = players["nanna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 2218, 237, 1006, 1851 }
	end
end
do
	local player = players["casthir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3911, 129, 328, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3911, 129, 328, 0 }
	end
end
do
	local player = players["gomigomi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 8119, 60, 102, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8119, 60, 102, 0 }
	end
end
do
	local player = players["eldorwyn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3128, 141, 370, 0 }
	end
end
do
	local player = players["ruida"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8492, 51, 82, 0 }
	end
end
do
	local player = players["gavistur"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1229, 181, 472, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 1229, 181, 472, 0 }
	end
end
do
	local player = players["putrefactus"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2291, 155, 415, 0 }
	end
end
do
	local player = players["dariadna"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6983, 82, 163, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6983, 82, 163, 0 }
	end
end
do
	local player = players["orererereo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6778, 85, 174, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6778, 85, 174, 0 }
	end
end
do
	local player = players["motokko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 1061, 184, 481, 0 }
	end
end
do
	local player = players["tasra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 261, 194, 524, 0 }
	end
end
do
	local player = players["faebojaentan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5001, 371, 1426, 4499 }
	end
end
do
	local player = players["brrka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5923, 304, 1052, 5328 }
	end
end
do
	local player = players["shike"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5771, 273, 781, 5191 }
	end
end
do
	local player = players["goteborg"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5905, 307, 1062, 5312 }
	end
end
do
	local player = players["voshka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5652, 345, 1271, 5084 }
	end
end
do
	local player = players["riggle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6198, 81, 197, 5162 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6198, 81, 197, 5162 }
	end
end
do
	local player = players["stresado"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7250, 160, 529, 6522 }
	end
end
do
	local player = players["llamadrama"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7208, 169, 558, 6484 }
	end
end
do
	local player = players["ojeygrant"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6229, 294, 1044, 5603 }
	end
end
do
	local player = players["kulitkelamin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7071, 191, 630, 6361 }
	end
end
do
	local player = players["zinray"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7152, 176, 589, 6433 }
	end
end
do
	local player = players["arhrow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5877, 323, 1194, 5286 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5877, 323, 1194, 5286 }
	end
end
do
	local player = players["glenord"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5322, 362, 1355, 4787 }
	end
end
do
	local player = players["nellemi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5391, 361, 1341, 4849 }
	end
end
do
	local player = players["edil"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6085, 308, 1109, 5474 }
	end
end
do
	local player = players["phowder"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6668, 248, 840, 5998 }
	end
end
do
	local player = players["krzywuska"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5754, 337, 1234, 5176 }
	end
end
do
	local player = players["uvall"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5838, 325, 1203, 5251 }
	end
end
do
	local player = players["gunball"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6227, 295, 1045, 5601 }
	end
end
do
	local player = players["erdmann"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6913, 219, 724, 6218 }
	end
end
do
	local player = players["isildurbane"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5955, 85, 212, 4960 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7769, 126, 379, 6791 }
	end
end
do
	local player = players["zanahoriax"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 3261, 18, 50, 2706 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3261, 18, 50, 2706 }
	end
end
do
	local player = players["lucisauria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7627, 134, 403, 6733 }
	end
end
do
	local player = players["sachagray"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4885, 407, 1471, 4208 }
	end
end
do
	local player = players["oneeightysix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4748, 413, 1498, 4089 }
	end
end
do
	local player = players["allyfrost"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6621, 82, 175, 4901 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6300, 339, 1115, 5427 }
	end
end
do
	local player = players["yogaflame"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5323, 395, 1391, 4585 }
	end
end
do
	local player = players["urach"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4753, 412, 1496, 4094 }
	end
end
do
	local player = players["pizarro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5632, 383, 1321, 4851 }
	end
end
do
	local player = players["bishess"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6260, 343, 1133, 5392 }
	end
end
do
	local player = players["beelzibub"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4859, 116, 256, 3597 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6698, 302, 943, 5770 }
	end
end
do
	local player = players["garythegrey"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 8504, 119, 272, 6828 }
	end
end
do
	local player = players["megica"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1781, 132, 304, 1319 }
	end
end
do
	local player = players["phusion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7037, 244, 748, 6062 }
	end
end
do
	local player = players["froznfiasco"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7229, 212, 610, 6227 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8525, 2, 2, 3027 }
	end
end
do
	local player = players["humanmalemag"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6908, 262, 824, 5950 }
	end
end
do
	local player = players["skendo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 599, 462, 1813, 516 }
	end
end
do
	local player = players["aqquaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5856, 375, 1266, 5044 }
	end
end
do
	local player = players["marieecurie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 10000, 1, 1, 3551 }
	end
end
do
	local player = players["rime"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7333, 56, 98, 5428 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7216, 215, 617, 6216 }
	end
end
do
	local player = players["shmongle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4546, 418, 1518, 3915 }
	end
end
do
	local player = players["ignaciouss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7295, 199, 572, 6284 }
	end
end
do
	local player = players["wigner"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7754, 152, 408, 6541 }
	end
end
do
	local player = players["enanonsuelo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7439, 173, 470, 6408 }
	end
end
do
	local player = players["kerossene"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9316, 14, 22, 6199 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6873, 267, 837, 5920 }
	end
end
do
	local player = players["magogx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5561, 386, 1343, 4790 }
	end
end
do
	local player = players["roazander"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6015, 361, 1212, 5181 }
	end
end
do
	local player = players["mfs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7334, 190, 542, 6318 }
	end
end
do
	local player = players["arweyin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5721, 107, 225, 4235 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5601, 385, 1333, 4825 }
	end
end
do
	local player = players["oom"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4597, 117, 261, 3403 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7189, 222, 635, 6192 }
	end
end
do
	local player = players["pimage"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5256, 397, 1405, 4528 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5256, 397, 1405, 4528 }
	end
end
do
	local player = players["holydood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1756, 475, 1710, 44 }
	end
end
do
	local player = players["ilyssia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5256, 351, 1087, 92 }
	end
end
do
	local player = players["turbogyatt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5907, 322, 938, 101 }
	end
end
do
	local player = players["yabaited"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5513, 344, 1028, 96 }
	end
end
do
	local player = players["arthadric"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7466, 146, 438, 5084 }
	end
end
do
	local player = players["svitki"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5168, 356, 1107, 91 }
	end
end
do
	local player = players["mykinkydope"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4670, 380, 1221, 84 }
	end
end
do
	local player = players["holyguard"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2639, 469, 1686, 57 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6641, 202, 666, 4522 }
	end
end
do
	local player = players["vepar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 3478, 432, 1494, 68 }
	end
end
do
	local player = players["konradkozak"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4176, 406, 1334, 77 }
	end
end
do
	local player = players["ninymxd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5889, 324, 942, 100 }
	end
end
do
	local player = players["vload"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9878, 18, 29, 235 }
	end
end
do
	local player = players["leadrel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4896, 316, 881, 85 }
	end
end
do
	local player = players["flashdunk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4338, 398, 1297, 80 }
	end
end
do
	local player = players["juviah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6457, 295, 812, 107 }
	end
end
do
	local player = players["shuberxx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4773, 277, 725, 82 }
	end
end
do
	local player = players["legel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4495, 390, 1261, 82 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6476, 215, 701, 4410 }
	end
end
do
	local player = players["salma"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7562, 241, 559, 124 }
	end
end
do
	local player = players["reddit"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7047, 263, 677, 115 }
	end
end
do
	local player = players["boostpala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9065, 116, 215, 160 }
	end
end
do
	local player = players["irathaya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7864, 129, 338, 2771 }
	end
end
do
	local player = players["bealatryx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5386, 283, 897, 2313 }
	end
end
do
	local player = players["flamekiss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5684, 242, 719, 2441 }
	end
end
do
	local player = players["eufra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7395, 150, 412, 2693 }
	end
end
do
	local player = players["nohaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7288, 158, 429, 2684 }
	end
end
do
	local player = players["scorchirian"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3775, 354, 1524, 1622 }
	end
end
do
	local player = players["bellepalle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7136, 168, 453, 2654 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8291, 75, 194, 5645 }
	end
end
do
	local player = players["balat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3840, 351, 1508, 1649 }
	end
end
do
	local player = players["dizzx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5053, 310, 1100, 2171 }
	end
end
do
	local player = players["aebb"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7429, 150, 451, 5059 }
	end
end
do
	local player = players["ceniska"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5995, 216, 633, 2512 }
	end
end
do
	local player = players["lemmyx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5391, 281, 889, 2316 }
	end
end
do
	local player = players["topzz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4405, 263, 901, 2999 }
	end
end
do
	local player = players["mcsadlo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7300, 162, 490, 4971 }
	end
end
do
	local player = players["gachidunkan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7706, 232, 526, 127 }
	end
end
do
	local player = players["sinae"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 8240, 121, 212, 99 }
	end
end
do
	local player = players["pannaboha"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 375, 334, 1155, 0 }
	end
end
do
	local player = players["anittaa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6414, 190, 431, 82 }
	end
end
do
	local player = players["albimelusine"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9149, 61, 103, 125 }
	end
end
do
	local player = players["loweyecue"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3655, 29, 60, 64 }
	end
end
do
	local player = players["skyleen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5371, 214, 556, 75 }
	end
end
do
	local player = players["dewy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6545, 207, 559, 5569 }
	end
end
do
	local player = players["feigyleigh"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6021, 257, 747, 5248 }
	end
end
do
	local player = players["rosealine"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 4794, 366, 1273, 4179 }
	end
end
do
	local player = players["condesa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6892, 191, 503, 5682 }
	end
end
do
	local player = players["skibidiputa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1226, 318, 1053, 9 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 1226, 318, 1053, 9 }
	end
end
do
	local player = players["kisska"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5666, 250, 661, 4939 }
	end
end
do
	local player = players["geengar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7314, 161, 323, 89 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2784, 413, 1569, 2427 }
	end
end
do
	local player = players["priborpriest"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5740, 289, 889, 5003 }
	end
end
do
	local player = players["hookch"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6095, 247, 701, 5313 }
	end
end
do
	local player = players["sashaxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6813, 21, 30, 80 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6813, 21, 30, 80 }
	end
end
do
	local player = players["namies"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1960, 302, 965, 50 }
	end
end
do
	local player = players["penancy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6181, 239, 663, 5388 }
	end
end
do
	local player = players["voodoocloud"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5876, 274, 821, 5122 }
	end
end
do
	local player = players["thick"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4037, 245, 716, 68 }
	end
end
do
	local player = players["prokopy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6089, 249, 708, 5308 }
	end
end
do
	local player = players["shymalli"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9483, 39, 63, 154 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5885, 273, 815, 5130 }
	end
end
do
	local player = players["lukretia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5444, 320, 1032, 4746 }
	end
end
do
	local player = players["vangart"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 5471, 315, 1015, 4769 }
	end
end
do
	local player = players["calina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6847, 207, 711, 6187 }
	end
end
do
	local player = players["barryheydoo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6050, 221, 803, 5466 }
	end
end
do
	local player = players["zrorretthgin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5956, 226, 818, 5381 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 8089, 91, 226, 7129 }
	end
end
do
	local player = players["xnary"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5117, 221, 838, 4510 }
	end
end
do
	local player = players["duckiie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 9217, 38, 74, 7670 }
	end
end
do
	local player = players["kistokai"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7697, 138, 447, 6954 }
	end
end
do
	local player = players["popolaprieta"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7432, 162, 532, 6715 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6860, 174, 632, 6046 }
	end
end
do
	local player = players["karkage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5988, 210, 781, 5278 }
	end
end
do
	local player = players["backsurgeon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6267, 199, 743, 5524 }
	end
end
do
	local player = players["kishandora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7841, 112, 318, 6911 }
	end
end
do
	local player = players["ferdax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 7024, 165, 580, 6191 }
	end
end
do
	local player = players["wtfvanish"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 8121, 89, 221, 7158 }
	end
end
do
	local player = players["andreutate"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6480, 153, 452, 5481 }
	end
end
do
	local player = players["flybyone"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5871, 212, 789, 5175 }
	end
end
do
	local player = players["yharon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 356, 309, 1059, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 356, 309, 1059, 0 }
	end
end
do
	local player = players["bakosi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4756, 214, 840, 4193 }
	end
end
do
	local player = players["elibelly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 1951, 224, 910, 1720 }
	end
end
do
	local player = players["hrenorezka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 2172, 223, 906, 1915 }
	end
end
do
	local player = players["eskalatorr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 2681, 222, 895, 2364 }
	end
end
do
	local player = players["anpc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5791, 198, 771, 5106 }
	end
end
do
	local player = players["chelavac"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3045, 269, 853, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3045, 269, 853, 0 }
	end
end
do
	local player = players["firzeen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 2973, 221, 891, 2621 }
	end
end
do
	local player = players["healingwave"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3102, 266, 846, 0 }
	end
end
do
	local player = players["aldeans"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7584, 137, 297, 3 }
	end
end
do
	local player = players["babytequi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6473, 180, 433, 0 }
	end
end
do
	local player = players["grasham"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6620, 177, 415, 0 }
	end
end
do
	local player = players["onlyshears"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6637, 175, 413, 0 }
	end
end
do
	local player = players["vasilx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 9845, 18, 20, 412 }
	end
end
do
	local player = players["awranges"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6065, 197, 483, 0 }
	end
end
do
	local player = players["krufkamilka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6629, 176, 414, 0 }
	end
end
do
	local player = players["alaching"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 9184, 53, 101, 221 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 9184, 53, 101, 221 }
	end
end
do
	local player = players["ratatin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7869, 123, 262, 6 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7869, 123, 262, 6 }
	end
end
do
	local player = players["elmoro"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2286, 290, 946, 0 }
	end
end
do
	local player = players["valnaara"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7853, 124, 264, 6 }
	end
end
do
	local player = players["wakwaw"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2416, 229, 679, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2416, 229, 679, 0 }
	end
end
do
	local player = players["eilani"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 1682, 304, 1020, 0 }
	end
end
do
	local player = players["tickled"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6710, 172, 404, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6710, 172, 404, 0 }
	end
end
do
	local player = players["kassah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 3412, 259, 808, 0 }
	end
end
do
	local player = players["totemmasterr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6098, 194, 479, 0 }
	end
end
do
	local player = players["dashamana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8073, 110, 237, 10 }
	end
end
do
	local player = players["toldaso"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8327, 98, 206, 16 }
	end
end
do
	local player = players["chamiglas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 6939, 166, 376, 0 }
	end
end
do
	local player = players["wollfram"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 710, 323, 1139, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 710, 323, 1139, 0 }
	end
end
do
	local player = players["gulululu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 9976, 4, 4, 667 }
	end
end
do
	local player = players["caciquejalin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2689, 195, 523, 0 }
	end
end
do
	local player = players["vaq"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 7780, 129, 273, 5 }
	end
end
do
	local player = players["vaskox"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 8824, 71, 145, 56 }
	end
end
do
	local player = players["elecktro"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][7] = { 2318, 289, 942, 0 }
	end
end
do
	local player = players["eliaz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5702, 414, 1684, 5497 }
	end
end
do
	local player = players["idamage"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6812, 227, 681, 6555 }
	end
end
do
	local player = players["kinkymagic"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6756, 313, 1127, 6512 }
	end
end
do
	local player = players["willijams"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5742, 409, 1668, 5535 }
	end
end
do
	local player = players["curseofwotlk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7010, 272, 927, 6757 }
	end
end
do
	local player = players["diabolos"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4347, 416, 1534, 4183 }
	end
end
do
	local player = players["warchoto"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6516, 338, 1293, 6281 }
	end
end
do
	local player = players["ejevichka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6468, 345, 1320, 6235 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5443, 297, 1021, 4967 }
	end
end
do
	local player = players["shierah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2911, 497, 2090, 2806 }
	end
end
do
	local player = players["praziquantel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6445, 349, 1337, 6213 }
	end
end
do
	local player = players["daestra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5568, 286, 983, 5081 }
	end
end
do
	local player = players["artstylle"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6431, 282, 904, 6188 }
	end
end
do
	local player = players["bloemfontijn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6326, 364, 1405, 6098 }
	end
end
do
	local player = players["kutau"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 1654, 501, 2147, 1594 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 1654, 501, 2147, 1594 }
	end
end
do
	local player = players["najella"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6183, 379, 1484, 5960 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 4114, 329, 1167, 3754 }
	end
end
do
	local player = players["brokolocko"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4891, 458, 1879, 4715 }
	end
end
do
	local player = players["untemi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6979, 281, 964, 6727 }
	end
end
do
	local player = players["bzezlock"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 8318, 119, 365, 7618 }
	end
end
do
	local player = players["dizzley"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 4221, 479, 1986, 4069 }
	end
end
do
	local player = players["onlyblacks"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6423, 352, 1343, 6192 }
	end
end
do
	local player = players["nazlock"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7466, 193, 622, 7197 }
	end
end
do
	local player = players["aesthly"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 7019, 274, 936, 6766 }
	end
end
do
	local player = players["abahlock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6529, 210, 677, 5958 }
	end
end
do
	local player = players["xernot"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5622, 420, 1707, 5419 }
	end
end
do
	local player = players["rayan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6458, 219, 711, 5893 }
	end
end
do
	local player = players["boostieone"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6161, 239, 824, 5623 }
	end
end
do
	local player = players["eyegouge"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6511, 214, 687, 5941 }
	end
end
do
	local player = players["nodotts"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5165, 269, 810, 4554 }
	end
end
do
	local player = players["sharonstonee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5087, 271, 816, 4486 }
	end
end
do
	local player = players["azais"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5039, 310, 1083, 4598 }
	end
end
do
	local player = players["whiffsee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3648, 292, 897, 3217 }
	end
end
do
	local player = players["mindmelter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 6435, 351, 1341, 6204 }
	end
end
do
	local player = players["moflau"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5649, 269, 885, 5155 }
	end
end
do
	local player = players["astramentos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6624, 200, 640, 6045 }
	end
end
do
	local player = players["nyhil"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6650, 198, 629, 6069 }
	end
end
do
	local player = players["daffh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6555, 209, 670, 5981 }
	end
end
do
	local player = players["sarexa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5050, 308, 1081, 4608 }
	end
end
do
	local player = players["batoulock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5984, 262, 884, 5461 }
	end
end
do
	local player = players["etwastot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6318, 229, 768, 5766 }
	end
end
do
	local player = players["piripincio"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 3861, 331, 1179, 3524 }
	end
end
do
	local player = players["ehsiug"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5561, 67, 183, 3883 }
	end
end
do
	local player = players["palipallet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6275, 204, 707, 5280 }
	end
end
do
	local player = players["perebor"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 5541, 68, 186, 3870 }
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6694, 156, 524, 5632 }
	end
end
do
	local player = players["jakesekirice"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6557, 174, 587, 5517 }
	end
end
do
	local player = players["kaiccy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5605, 247, 925, 4716 }
	end
end
do
	local player = players["brutalizerum"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 5944, 224, 832, 5001 }
	end
end
do
	local player = players["henrycleavil"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][7] = { 2455, 78, 227, 1714 }
	end
end
do
	local player = players["hadgall"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][7] = { 6271, 205, 710, 5276 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
