-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "togc"
local chunkStartIndex = 26043
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["necromanceqt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8478, 205, 372, 2399 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9101, 169, 292, 10954 }
	end
end
do
	local player = players["fdark"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4501, 584, 1341, 2047 }
	end
end
do
	local player = players["gunsandroses"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3069, 721, 1690, 1946 }
	end
end
do
	local player = players["stuckycow"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8888, 156, 272, 2476 }
	end
end
do
	local player = players["thulam"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5334, 514, 1138, 2105 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7078, 474, 947, 9482 }
	end
end
do
	local player = players["aiuda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1879, 810, 1980, 1846 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1564, 391, 801, 2142 }
	end
end
do
	local player = players["radeciga"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1489, 399, 826, 2040 }
	end
end
do
	local player = players["onechonkiboi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8781, 168, 298, 2457 }
	end
end
do
	local player = players["maliice"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7843, 271, 518, 2312 }
	end
end
do
	local player = players["heglas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4215, 1251, 2833, 6569 }
	end
end
do
	local player = players["put"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4809, 554, 1266, 2064 }
	end
end
do
	local player = players["icytouchqt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3660, 667, 1546, 1988 }
	end
end
do
	local player = players["aelaen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5605, 486, 1072, 2122 }
	end
end
do
	local player = players["jaskierson"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2089, 796, 1929, 1866 }
	end
end
do
	local player = players["holesheet"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 44, 936, 2437, 52 }
	end
end
do
	local player = players["bulbka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8240, 230, 430, 2357 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1390, 409, 847, 1904 }
	end
end
do
	local player = players["lichbourne"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6163, 434, 936, 2168 }
	end
end
do
	local player = players["devilstearss"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5966, 455, 984, 2152 }
	end
end
do
	local player = players["kavliariis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8802, 165, 293, 2462 }
	end
end
do
	local player = players["corpsepile"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1521, 395, 820, 2083 }
	end
end
do
	local player = players["edknight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1874, 350, 735, 2567 }
	end
end
do
	local player = players["covidspred"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9339, 93, 162, 2630 }
	end
end
do
	local player = players["pintsized"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9274, 102, 178, 2599 }
	end
end
do
	local player = players["perkinqlo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4415, 595, 1362, 2040 }
	end
end
do
	local player = players["noont"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5802, 210, 435, 7949 }
	end
end
do
	local player = players["dkrani"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5084, 267, 569, 6965 }
	end
end
do
	local player = players["minisaurawr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5296, 250, 530, 7255 }
	end
end
do
	local player = players["froostt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5917, 653, 1323, 8956 }
	end
end
do
	local player = players["feverish"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5006, 275, 582, 6858 }
	end
end
do
	local player = players["yazinet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5515, 236, 499, 7554 }
	end
end
do
	local player = players["larjanus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6976, 134, 262, 8982 }
	end
end
do
	local player = players["frozenally"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7613, 105, 207, 9413 }
	end
end
do
	local player = players["shockwawee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7740, 98, 196, 9471 }
	end
end
do
	local player = players["eljean"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4834, 552, 1260, 2066 }
	end
end
do
	local player = players["dzukella"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3739, 318, 682, 5123 }
	end
end
do
	local player = players["duriff"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5454, 241, 509, 7471 }
	end
end
do
	local player = players["silvermortal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6161, 615, 1244, 9051 }
	end
end
do
	local player = players["djedknight"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4244, 1245, 2821, 6613 }
	end
end
do
	local player = players["cokoloo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5388, 840, 1761, 8396 }
	end
end
do
	local player = players["nevervax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6946, 491, 990, 9405 }
	end
end
do
	local player = players["actuallydead"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6967, 489, 983, 9416 }
	end
end
do
	local player = players["yomato"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5425, 824, 1715, 8454 }
	end
end
do
	local player = players["keyadk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4568, 1166, 2596, 7118 }
	end
end
do
	local player = players["coadk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9790, 46, 69, 12230 }
	end
end
do
	local player = players["chymazblu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8527, 248, 478, 10453 }
	end
end
do
	local player = players["siacoin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1517, 848, 2113, 1773 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4825, 1071, 2366, 7519 }
	end
end
do
	local player = players["siniigamii"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9466, 104, 174, 11467 }
	end
end
do
	local player = players["lampolo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7594, 393, 780, 9786 }
	end
end
do
	local player = players["yryd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7946, 344, 666, 10000 }
	end
end
do
	local player = players["fallenrunes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6859, 505, 1018, 9371 }
	end
end
do
	local player = players["proyectic"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5372, 847, 1776, 8372 }
	end
end
do
	local player = players["anounymous"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5480, 790, 1636, 8540 }
	end
end
do
	local player = players["velorst"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5597, 732, 1504, 8721 }
	end
end
do
	local player = players["amundsen"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4368, 1217, 2741, 6807 }
	end
end
do
	local player = players["koteykin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9185, 155, 265, 11005 }
	end
end
do
	local player = players["grigin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9429, 111, 186, 11369 }
	end
end
do
	local player = players["zatracen"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4274, 1238, 2800, 6660 }
	end
end
do
	local player = players["erectuz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6038, 634, 1284, 8999 }
	end
end
do
	local player = players["yethizad"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8447, 263, 504, 10393 }
	end
end
do
	local player = players["eldrogada"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8863, 209, 369, 10704 }
	end
end
do
	local player = players["sanemii"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4638, 1140, 2535, 7227 }
	end
end
do
	local player = players["cusdamatto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5104, 967, 2083, 7953 }
	end
end
do
	local player = players["krysthyan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4775, 1255, 2515, 8208 }
	end
end
do
	local player = players["starcool"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9240, 218, 342, 11295 }
	end
end
do
	local player = players["laplaya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3928, 1750, 3718, 6752 }
	end
end
do
	local player = players["dixo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9409, 171, 266, 11556 }
	end
end
do
	local player = players["avaree"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9485, 147, 232, 11689 }
	end
end
do
	local player = players["immamariuano"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3378, 1918, 4169, 5806 }
	end
end
do
	local player = players["luminance"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4588, 1379, 2815, 7887 }
	end
end
do
	local player = players["dimjkeekek"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6502, 832, 1570, 9259 }
	end
end
do
	local player = players["helltree"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4703, 1307, 2625, 8085 }
	end
end
do
	local player = players["moondudu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7681, 587, 1041, 10017 }
	end
end
do
	local player = players["druidbinder"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7356, 647, 1187, 9797 }
	end
end
do
	local player = players["tlione"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4902, 1170, 2307, 8426 }
	end
end
do
	local player = players["broasters"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7929, 544, 930, 10171 }
	end
end
do
	local player = players["ech"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4825, 1217, 2421, 8295 }
	end
end
do
	local player = players["druzuss"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9541, 133, 207, 11793 }
	end
end
do
	local player = players["maximumwild"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7862, 557, 960, 10129 }
	end
end
do
	local player = players["healsomeheal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6475, 838, 1582, 9246 }
	end
end
do
	local player = players["noaria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8589, 395, 634, 10671 }
	end
end
do
	local player = players["tromale"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4829, 1215, 2416, 8302 }
	end
end
do
	local player = players["astarid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4514, 1415, 2881, 7754 }
	end
end
do
	local player = players["kerrycanalga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9254, 213, 332, 11325 }
	end
end
do
	local player = players["mymistress"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9139, 246, 387, 11164 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7330, 60, 112, 59 }
	end
end
do
	local player = players["chiquenlirel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4330, 1554, 3214, 7443 }
	end
end
do
	local player = players["midzimon"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4768, 1256, 2499, 8191 }
	end
end
do
	local player = players["eternaldruid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3256, 1935, 4219, 5597 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8575, 36, 59, 104 }
	end
end
do
	local player = players["milkitits"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7458, 624, 1141, 9871 }
	end
end
do
	local player = players["bamboomie"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9093, 259, 408, 11114 }
	end
end
do
	local player = players["belecow"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9719, 87, 124, 12133 }
	end
end
do
	local player = players["moomoomoomoo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5258, 1143, 2221, 8427 }
	end
end
do
	local player = players["serafina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6428, 847, 1603, 9230 }
	end
end
do
	local player = players["troldudu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7767, 564, 992, 10063 }
	end
end
do
	local player = players["kyougen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7683, 582, 1029, 10003 }
	end
end
do
	local player = players["nadaren"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4279, 1699, 3563, 6858 }
	end
end
do
	local player = players["valeshii"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7075, 702, 1313, 9617 }
	end
end
do
	local player = players["wisteris"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2145, 1997, 4333, 3439 }
	end
end
do
	local player = players["yeh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4273, 1694, 3546, 6849 }
	end
end
do
	local player = players["krevedka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8865, 314, 498, 10892 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8511, 220, 370, 11116 }
	end
end
do
	local player = players["zdarkdevil"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8682, 363, 586, 10728 }
	end
end
do
	local player = players["durahausen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9360, 185, 288, 11488 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5339, 104, 204, 16 }
	end
end
do
	local player = players["chillbruf"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9344, 189, 295, 11478 }
	end
end
do
	local player = players["taphu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8943, 25, 44, 119 }
	end
end
do
	local player = players["rivermane"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3620, 142, 270, 5 }
	end
end
do
	local player = players["infuzija"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8905, 300, 476, 10914 }
	end
end
do
	local player = players["treelee"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9242, 217, 341, 11306 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 1765, 183, 340, 1 }
	end
end
do
	local player = players["jensenjr"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6370, 860, 1629, 9203 }
	end
end
do
	local player = players["sweetbanana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5530, 1040, 2006, 8790 }
	end
end
do
	local player = players["bairyhalls"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6856, 753, 1411, 9483 }
	end
end
do
	local player = players["millora"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9164, 239, 376, 11205 }
	end
end
do
	local player = players["laraein"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7173, 680, 1269, 9686 }
	end
end
do
	local player = players["cikicikiboom"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8285, 470, 770, 10432 }
	end
end
do
	local player = players["firebirdy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9264, 210, 331, 11350 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6683, 76, 136, 46 }
	end
end
do
	local player = players["throweryx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7200, 674, 1257, 9697 }
	end
end
do
	local player = players["pivaldi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7739, 575, 1015, 10055 }
	end
end
do
	local player = players["spelhover"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3599, 1861, 4027, 6186 }
	end
end
do
	local player = players["katerok"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7601, 601, 1077, 9952 }
	end
end
do
	local player = players["alpinepro"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9041, 275, 431, 11061 }
	end
end
do
	local player = players["akotche"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4676, 1328, 2671, 8038 }
	end
end
do
	local player = players["hruonnt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9010, 284, 445, 11043 }
	end
end
do
	local player = players["makanixdr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8624, 35, 57, 106 }
	end
end
do
	local player = players["jirafo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6424, 848, 1605, 9230 }
	end
end
do
	local player = players["felina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5601, 1019, 1974, 8826 }
	end
end
do
	local player = players["gatitamiau"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8919, 162, 275, 11479 }
	end
end
do
	local player = players["bobe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6389, 449, 916, 10140 }
	end
end
do
	local player = players["negotive"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8583, 211, 360, 11170 }
	end
end
do
	local player = players["cremebrulee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8350, 243, 419, 11041 }
	end
end
do
	local player = players["illgetlucky"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8678, 197, 336, 11260 }
	end
end
do
	local player = players["caitou"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6243, 466, 953, 10071 }
	end
end
do
	local player = players["blindcat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6728, 408, 830, 10302 }
	end
end
do
	local player = players["parkow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6914, 387, 783, 10401 }
	end
end
do
	local player = players["czikibansior"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9006, 150, 253, 11543 }
	end
end
do
	local player = players["tantonferal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5556, 542, 1130, 9793 }
	end
end
do
	local player = players["crazykek"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5979, 498, 1020, 9957 }
	end
end
do
	local player = players["pinodevinte"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5963, 499, 1024, 9950 }
	end
end
do
	local player = players["aarcon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4959, 770, 1722, 8740 }
	end
end
do
	local player = players["neunferal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7178, 359, 716, 10508 }
	end
end
do
	local player = players["kiwizoon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9882, 21, 31, 13036 }
	end
end
do
	local player = players["golqmkotor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6717, 410, 833, 10298 }
	end
end
do
	local player = players["kitkeet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7979, 284, 513, 10834 }
	end
end
do
	local player = players["blerd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2127, 175, 324, 2 }
	end
end
do
	local player = players["smellyfeet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8725, 190, 324, 11291 }
	end
end
do
	local player = players["micio"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8891, 166, 282, 11439 }
	end
end
do
	local player = players["wantedcat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4985, 758, 1693, 8786 }
	end
end
do
	local player = players["pepedudu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8145, 268, 471, 10924 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9558, 13, 19, 162 }
	end
end
do
	local player = players["ismokeweed"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7478, 326, 640, 10638 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5294, 105, 206, 16 }
	end
end
do
	local player = players["penetronn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7695, 309, 585, 10720 }
	end
end
do
	local player = players["tromlevognen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6894, 389, 788, 10393 }
	end
end
do
	local player = players["slowfinger"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5299, 639, 1395, 9340 }
	end
end
do
	local player = players["icepeakcz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8713, 191, 327, 11283 }
	end
end
do
	local player = players["bubolina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5931, 501, 1032, 9935 }
	end
end
do
	local player = players["rejuju"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 811, 206, 375, 1 }
	end
end
do
	local player = players["twisstzz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 407, 213, 392, 0 }
	end
end
do
	local player = players["aarress"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8071, 470, 973, 9640 }
	end
end
do
	local player = players["aimlord"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8751, 318, 630, 10168 }
	end
end
do
	local player = players["fulmetali"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7070, 712, 1477, 9029 }
	end
end
do
	local player = players["felp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6937, 743, 1544, 8950 }
	end
end
do
	local player = players["allberijita"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7314, 657, 1354, 9160 }
	end
end
do
	local player = players["rengarka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4889, 61, 152, 6583 }
	end
end
do
	local player = players["goldeneg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3772, 1537, 3642, 6746 }
	end
end
do
	local player = players["zexonina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7888, 519, 1065, 9493 }
	end
end
do
	local player = players["kociczka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2260, 1991, 4914, 4042 }
	end
end
do
	local player = players["upermost"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8777, 312, 617, 10194 }
	end
end
do
	local player = players["polvoraseca"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8087, 466, 965, 9644 }
	end
end
do
	local player = players["neithzs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3875, 1480, 3500, 6930 }
	end
end
do
	local player = players["toonelo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6778, 776, 1624, 8861 }
	end
end
do
	local player = players["vitka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3872, 1483, 3510, 6924 }
	end
end
do
	local player = players["perkyarrow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9240, 199, 384, 10603 }
	end
end
do
	local player = players["ookotsu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9222, 203, 393, 10588 }
	end
end
do
	local player = players["telleri"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6113, 46, 102, 8231 }
	end
end
do
	local player = players["overloaded"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3003, 1873, 4597, 5370 }
	end
end
do
	local player = players["srcupido"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7291, 661, 1366, 9152 }
	end
end
do
	local player = players["blasfemy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5649, 999, 2193, 8210 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5848, 51, 113, 7875 }
	end
end
do
	local player = players["drhood"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5234, 1088, 2402, 8004 }
	end
end
do
	local player = players["hassuy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8783, 310, 614, 10198 }
	end
end
do
	local player = players["szparken"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4155, 1314, 3043, 7430 }
	end
end
do
	local player = players["zxhuntressxz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5905, 941, 2064, 8357 }
	end
end
do
	local player = players["marksmanx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7424, 631, 1299, 9237 }
	end
end
do
	local player = players["gangorca"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3398, 1735, 4182, 6076 }
	end
end
do
	local player = players["killshots"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2295, 1985, 4905, 4104 }
	end
end
do
	local player = players["marron"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5204, 1095, 2417, 7992 }
	end
end
do
	local player = players["coconeza"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4631, 1196, 2706, 7737 }
	end
end
do
	local player = players["kasanekra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7606, 586, 1207, 9325 }
	end
end
do
	local player = players["kraziebone"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3274, 1787, 4338, 5855 }
	end
end
do
	local player = players["tesay"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3107, 1841, 4503, 5556 }
	end
end
do
	local player = players["jonbovie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5399, 1050, 2319, 8081 }
	end
end
do
	local player = players["huntaro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3403, 1733, 4177, 6085 }
	end
end
do
	local player = players["marader"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3395, 1737, 4187, 6071 }
	end
end
do
	local player = players["vatn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3629, 1621, 3864, 6490 }
	end
end
do
	local player = players["zottohunt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3616, 1629, 3880, 6466 }
	end
end
do
	local player = players["sunaya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4040, 1148, 2202, 8868 }
	end
end
do
	local player = players["ra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 290, 1605, 3245, 635 }
	end
end
do
	local player = players["magith"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6630, 595, 1100, 10785 }
	end
end
do
	local player = players["jinwakakax"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6027, 12, 20, 7751 }
	end
end
do
	local player = players["lovemygoose"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7167, 514, 925, 11048 }
	end
end
do
	local player = players["asztrid"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9077, 184, 302, 12468 }
	end
end
do
	local player = players["synbi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8890, 219, 363, 12268 }
	end
end
do
	local player = players["killingorder"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4578, 913, 1769, 9738 }
	end
end
do
	local player = players["kaeilthas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3918, 1228, 2413, 8600 }
	end
end
do
	local player = players["dupedavka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3707, 1320, 2628, 8137 }
	end
end
do
	local player = players["cyberciganka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7295, 492, 883, 11119 }
	end
end
do
	local player = players["judgewype"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4759, 889, 1710, 9836 }
	end
end
do
	local player = players["zerohotty"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3189, 1479, 2955, 7000 }
	end
end
do
	local player = players["sarahmara"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6026, 693, 1274, 10429 }
	end
end
do
	local player = players["trmage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8326, 318, 547, 11793 }
	end
end
do
	local player = players["vuurschieter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9601, 87, 131, 13236 }
	end
end
do
	local player = players["eurekamage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6578, 607, 1117, 10756 }
	end
end
do
	local player = players["annabolicx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1708, 1598, 3227, 3749 }
	end
end
do
	local player = players["chichomage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9215, 161, 257, 12631 }
	end
end
do
	local player = players["atamblaster"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8415, 302, 518, 11866 }
	end
end
do
	local player = players["dunksten"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2801, 1536, 3090, 6147 }
	end
end
do
	local player = players["jetstrike"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2912, 1520, 3057, 6391 }
	end
end
do
	local player = players["malleaborj"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5386, 793, 1458, 10089 }
	end
end
do
	local player = players["arragodx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8280, 325, 562, 11761 }
	end
end
do
	local player = players["pitufaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5290, 819, 1537, 10075 }
	end
end
do
	local player = players["livingbombx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2549, 1564, 3150, 5594 }
	end
end
do
	local player = players["retame"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3129, 1489, 2980, 6868 }
	end
end
do
	local player = players["liftfreaker"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3284, 1456, 2906, 7207 }
	end
end
do
	local player = players["stellimage"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4213, 1054, 2058, 9247 }
	end
end
do
	local player = players["kuchiki"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8710, 256, 595, 3283 }
	end
end
do
	local player = players["moremana"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3241, 1119, 3113, 955 }
	end
end
do
	local player = players["holyjo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7617, 468, 795, 219 }
	end
end
do
	local player = players["palahop"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9265, 161, 246, 283 }
	end
end
do
	local player = players["vadyasmelec"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7315, 719, 1349, 9746 }
	end
end
do
	local player = players["estranja"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3283, 1082, 2239, 137 }
	end
end
do
	local player = players["isnara"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9292, 156, 237, 285 }
	end
end
do
	local player = players["instyvibes"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8448, 325, 518, 243 }
	end
end
do
	local player = players["rextroy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7950, 407, 684, 228 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9301, 198, 352, 11411 }
	end
end
do
	local player = players["skyelumis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6918, 565, 1028, 203 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9277, 206, 364, 11385 }
	end
end
do
	local player = players["heavenjke"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7740, 444, 754, 222 }
	end
end
do
	local player = players["annomis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7506, 485, 832, 216 }
	end
end
do
	local player = players["bunnyhater"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7455, 491, 849, 215 }
	end
end
do
	local player = players["ninamaria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5240, 825, 1587, 171 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9509, 106, 227, 3816 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5323, 1161, 2349, 8767 }
	end
end
do
	local player = players["caukundo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5786, 742, 1405, 181 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6301, 955, 1858, 9218 }
	end
end
do
	local player = players["paxz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2269, 1209, 2577, 120 }
	end
end
do
	local player = players["cocaiinaa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6315, 659, 1229, 191 }
	end
end
do
	local player = players["kilimoony"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7989, 397, 671, 229 }
	end
end
do
	local player = players["missukraine"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9604, 120, 200, 11956 }
	end
end
do
	local player = players["ancientkaly"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8199, 367, 601, 236 }
	end
end
do
	local player = players["kalydivine"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6828, 580, 1058, 201 }
	end
end
do
	local player = players["setuppala"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7261, 730, 1376, 9714 }
	end
end
do
	local player = players["nevadpsagain"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7323, 511, 893, 212 }
	end
end
do
	local player = players["oldwoolf"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9177, 230, 414, 11225 }
	end
end
do
	local player = players["ox"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2143, 1228, 2619, 117 }
	end
end
do
	local player = players["winpy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2134, 1229, 2622, 116 }
	end
end
do
	local player = players["hewz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3094, 1116, 2302, 134 }
	end
end
do
	local player = players["entertained"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5940, 710, 1835, 2272 }
	end
end
do
	local player = players["excelsaga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7971, 402, 677, 229 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7042, 553, 1363, 2648 }
	end
end
do
	local player = players["fatalitypala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1666, 1280, 2778, 106 }
	end
end
do
	local player = players["malignohtps"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4485, 920, 2540, 1582 }
	end
end
do
	local player = players["kocsma"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9737, 53, 122, 4185 }
	end
end
do
	local player = players["oladino"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2602, 1173, 2466, 125 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2639, 1208, 3390, 792 }
	end
end
do
	local player = players["dedenko"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8640, 269, 627, 3247 }
	end
end
do
	local player = players["punpu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6288, 664, 1238, 190 }
	end
end
do
	local player = players["noedtz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6351, 653, 1681, 2429 }
	end
end
do
	local player = players["ayonna"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3427, 1065, 2191, 139 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8008, 389, 918, 2974 }
	end
end
do
	local player = players["kronoptwo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5993, 705, 1846, 2307 }
	end
end
do
	local player = players["nicode"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7146, 539, 1315, 2686 }
	end
end
do
	local player = players["kylindor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6412, 640, 1653, 2447 }
	end
end
do
	local player = players["japierdole"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4111, 969, 2661, 1271 }
	end
end
do
	local player = players["sacrokilla"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8966, 205, 477, 3432 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4325, 1624, 3400, 7804 }
	end
end
do
	local player = players["praimut"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8734, 250, 584, 3300 }
	end
end
do
	local player = players["jadyzxx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9248, 153, 347, 3627 }
	end
end
do
	local player = players["borlord"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7420, 692, 1296, 9800 }
	end
end
do
	local player = players["lemoniadka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2824, 1185, 3305, 832 }
	end
end
do
	local player = players["hanziepala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 437, 1479, 4404, 297 }
	end
end
do
	local player = players["webonn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7552, 465, 1128, 2824 }
	end
end
do
	local player = players["desttry"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6825, 581, 1059, 201 }
	end
end
do
	local player = players["zoval"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8458, 313, 711, 3157 }
	end
end
do
	local player = players["cajafuertee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8295, 347, 786, 3090 }
	end
end
do
	local player = players["saacredman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6179, 678, 1760, 2367 }
	end
end
do
	local player = players["valantor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7391, 489, 1202, 2764 }
	end
end
do
	local player = players["ragsol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2100, 1277, 3638, 679 }
	end
end
do
	local player = players["minjakikotor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7037, 554, 1365, 2648 }
	end
end
do
	local player = players["fiutel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2291, 1249, 3550, 716 }
	end
end
do
	local player = players["carneirinha"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9144, 176, 395, 3558 }
	end
end
do
	local player = players["budzogan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9800, 41, 93, 4362 }
	end
end
do
	local player = players["joylight"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9295, 155, 236, 285 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3767, 1974, 4265, 6798 }
	end
end
do
	local player = players["hollysmashh"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8813, 335, 597, 10772 }
	end
end
do
	local player = players["helltribute"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8012, 553, 999, 10165 }
	end
end
do
	local player = players["bablos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9390, 173, 307, 11558 }
	end
end
do
	local player = players["inttolerant"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8303, 474, 853, 10357 }
	end
end
do
	local player = players["bizrazzwix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9695, 92, 154, 12175 }
	end
end
do
	local player = players["dazel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5667, 1079, 2176, 8929 }
	end
end
do
	local player = players["tratatatata"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9663, 103, 170, 12101 }
	end
end
do
	local player = players["sintetix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9320, 138, 314, 3675 }
	end
end
do
	local player = players["valanars"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8073, 375, 888, 3007 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4433, 1531, 3182, 7999 }
	end
end
do
	local player = players["wts"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7974, 564, 1018, 10134 }
	end
end
do
	local player = players["vindication"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 67, 2265, 5018, 121 }
	end
end
do
	local player = players["kremcaramelx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8635, 384, 686, 10606 }
	end
end
do
	local player = players["notdekoms"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7563, 476, 813, 217 }
	end
end
do
	local player = players["snippala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6953, 566, 1404, 2621 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7847, 591, 1082, 10050 }
	end
end
do
	local player = players["nairdap"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8251, 488, 879, 10312 }
	end
end
do
	local player = players["whitestyle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9719, 85, 142, 12238 }
	end
end
do
	local player = players["acidream"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9886, 35, 58, 13154 }
	end
end
do
	local player = players["futureqs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1093, 1402, 4102, 467 }
	end
end
do
	local player = players["wienerman"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7924, 572, 1043, 10101 }
	end
end
do
	local player = players["lidoris"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 575, 1442, 3270, 47 }
	end
end
do
	local player = players["waawa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6646, 607, 1545, 2525 }
	end
end
do
	local player = players["hongola"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9701, 90, 151, 12184 }
	end
end
do
	local player = players["vpn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8090, 532, 960, 10205 }
	end
end
do
	local player = players["givemoreds"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4271, 959, 1910, 155 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4432, 1534, 3186, 7996 }
	end
end
do
	local player = players["biemkatotok"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3718, 2001, 4315, 6709 }
	end
end
do
	local player = players["edvina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9257, 151, 343, 3630 }
	end
end
do
	local player = players["krevet"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7418, 693, 1297, 9799 }
	end
end
do
	local player = players["tenten"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7353, 507, 883, 213 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4570, 1404, 2917, 8245 }
	end
end
do
	local player = players["divinevil"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4400, 1557, 3243, 7938 }
	end
end
do
	local player = players["cioccolate"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7363, 495, 1215, 2757 }
	end
end
do
	local player = players["lightbinder"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6345, 654, 1219, 191 }
	end
end
do
	local player = players["vynielis"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4863, 872, 2366, 1824 }
	end
end
do
	local player = players["islanzaddi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5659, 1081, 2180, 8924 }
	end
end
do
	local player = players["ivanns"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5054, 1214, 2484, 8631 }
	end
end
do
	local player = players["teiwas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7715, 623, 1148, 9973 }
	end
end
do
	local player = players["vikktoria"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7542, 668, 1235, 9867 }
	end
end
do
	local player = players["prostifrosti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9586, 123, 209, 11911 }
	end
end
do
	local player = players["mellynara"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8912, 215, 502, 3398 }
	end
end
do
	local player = players["spastic"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4630, 1349, 2792, 8353 }
	end
end
do
	local player = players["infusion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8906, 312, 550, 10848 }
	end
end
do
	local player = players["emmanuelz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3512, 2063, 4501, 6336 }
	end
end
do
	local player = players["bujingyun"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6000, 1012, 2009, 9085 }
	end
end
do
	local player = players["gubby"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5841, 1043, 2089, 9010 }
	end
end
do
	local player = players["aledrinia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4367, 1582, 3310, 7880 }
	end
end
do
	local player = players["soullreaver"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3634, 1038, 2122, 144 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4519, 1454, 3017, 8154 }
	end
end
do
	local player = players["anturiel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9922, 19, 27, 433 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9980, 6, 11, 15552 }
	end
end
do
	local player = players["jackof"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 179, 897, 1754, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3664, 1725, 3821, 6623 }
	end
end
do
	local player = players["plugin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8801, 135, 215, 189 }
	end
end
do
	local player = players["silvershower"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7260, 578, 1184, 9974 }
	end
end
do
	local player = players["pompompidou"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4465, 578, 989, 117 }
	end
end
do
	local player = players["lireis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7503, 525, 1079, 10145 }
	end
end
do
	local player = players["ganndallf"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3092, 681, 1234, 101 }
	end
end
do
	local player = players["aicomocura"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7213, 591, 1204, 9937 }
	end
end
do
	local player = players["annlia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4678, 555, 951, 119 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4729, 1108, 2297, 8548 }
	end
end
do
	local player = players["parax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2890, 1883, 4199, 5224 }
	end
end
do
	local player = players["beniego"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7897, 442, 909, 10404 }
	end
end
do
	local player = players["discotteka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1042, 836, 1600, 25 }
	end
end
do
	local player = players["amritpriest"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4816, 1080, 2239, 8614 }
	end
end
do
	local player = players["madmais"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7888, 243, 378, 156 }
	end
end
do
	local player = players["dedopope"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4796, 542, 930, 120 }
	end
end
do
	local player = players["curvas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7211, 588, 1185, 9910 }
	end
end
do
	local player = players["loudwaves"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4022, 613, 1068, 113 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7906, 440, 905, 10410 }
	end
end
do
	local player = players["shchors"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7017, 323, 529, 142 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5351, 962, 1987, 8864 }
	end
end
do
	local player = players["glasscandy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6683, 715, 1409, 9577 }
	end
end
do
	local player = players["easykillyoup"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9244, 88, 133, 216 }
	end
end
do
	local player = players["blindikchek"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7176, 310, 505, 143 }
	end
end
do
	local player = players["realpithia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9588, 52, 73, 263 }
	end
end
do
	local player = players["ublianka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7960, 232, 362, 158 }
	end
end
do
	local player = players["benfflay"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8403, 186, 280, 167 }
	end
end
do
	local player = players["trolita"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2711, 717, 1302, 95 }
	end
end
do
	local player = players["holytenka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3636, 642, 1137, 109 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5949, 860, 1750, 9198 }
	end
end
do
	local player = players["dzsindzser"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 168, 898, 1756, 0 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4098, 1541, 3334, 7408 }
	end
end
do
	local player = players["lethalholy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5669, 451, 774, 128 }
	end
end
do
	local player = players["gordona"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 829, 845, 1638, 17 }
	end
end
do
	local player = players["honzi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3951, 35, 50, 112 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7160, 607, 1227, 9907 }
	end
end
do
	local player = players["kaeirayice"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8924, 122, 193, 194 }
	end
end
do
	local player = players["wwyg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9737, 32, 48, 317 }
	end
end
do
	local player = players["boltinika"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5679, 27, 36, 137 }
	end
end
do
	local player = players["fructal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4683, 1154, 2392, 8464 }
	end
end
do
	local player = players["swagarian"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7827, 460, 939, 10363 }
	end
end
do
	local player = players["mspp"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4591, 1217, 2529, 8298 }
	end
end
do
	local player = players["taneshima"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4269, 593, 1024, 115 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9080, 193, 398, 11543 }
	end
end
do
	local player = players["everinna"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7190, 598, 1214, 9918 }
	end
end
do
	local player = players["healina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4667, 557, 953, 119 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8328, 354, 723, 10761 }
	end
end
do
	local player = players["lisany"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7510, 523, 1076, 10157 }
	end
end
do
	local player = players["marriya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4276, 1426, 3032, 7730 }
	end
end
do
	local player = players["myracle"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4302, 1413, 2990, 7775 }
	end
end
do
	local player = players["posiible"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7218, 590, 1202, 9940 }
	end
end
do
	local player = players["xshdw"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7188, 599, 1215, 9915 }
	end
end
do
	local player = players["xeemy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5814, 884, 1808, 9135 }
	end
end
do
	local player = players["nairex"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6511, 760, 1507, 9508 }
	end
end
do
	local player = players["eimepr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7811, 459, 936, 10331 }
	end
end
do
	local player = players["velastela"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2044, 760, 1391, 76 }
	end
end
do
	local player = players["sckan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3289, 665, 1199, 104 }
	end
end
do
	local player = players["sopitadarroz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4192, 1479, 3165, 7577 }
	end
end
do
	local player = players["jacetms"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7353, 555, 1132, 10034 }
	end
end
do
	local player = players["priestdemon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7135, 607, 1225, 9866 }
	end
end
do
	local player = players["takayasho"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6989, 329, 527, 141 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7767, 468, 949, 10284 }
	end
end
do
	local player = players["alordiish"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 246, 879, 1705, 1 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5298, 975, 1997, 8837 }
	end
end
do
	local player = players["maxpriest"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4066, 600, 1033, 113 }
	end
end
do
	local player = players["sergiorossi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9694, 59, 131, 12603 }
	end
end
do
	local player = players["rherswetrust"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3155, 1838, 4081, 5472 }
	end
end
do
	local player = players["displazija"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6968, 645, 1288, 9766 }
	end
end
do
	local player = players["evoshodow"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7609, 505, 1033, 10223 }
	end
end
do
	local player = players["laily"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7006, 636, 1264, 9778 }
	end
end
do
	local player = players["ruupsty"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9387, 121, 263, 11977 }
	end
end
do
	local player = players["obscurant"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6114, 412, 678, 131 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3660, 1746, 3861, 6348 }
	end
end
do
	local player = players["virgensita"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9395, 120, 262, 12013 }
	end
end
do
	local player = players["subsovich"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 773, 849, 1648, 14 }
	end
end
do
	local player = players["jimwildaea"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9584, 81, 186, 12355 }
	end
end
do
	local player = players["anaksagoras"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9856, 30, 63, 13080 }
	end
end
do
	local player = players["xombrita"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4046, 1571, 3411, 7314 }
	end
end
do
	local player = players["careerax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4660, 1174, 2431, 8424 }
	end
end
do
	local player = players["drsmokeqt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7920, 437, 899, 10425 }
	end
end
do
	local player = players["madop"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4611, 564, 963, 119 }
	end
end
do
	local player = players["nolliq"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3754, 1692, 3735, 6786 }
	end
end
do
	local player = players["lotrik"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7797, 465, 952, 10341 }
	end
end
do
	local player = players["rhl"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4112, 1534, 3308, 7434 }
	end
end
do
	local player = players["aconjamrmot"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6894, 667, 1342, 9739 }
	end
end
do
	local player = players["vaglef"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6845, 681, 1363, 9705 }
	end
end
do
	local player = players["darkdeathvxv"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4188, 1483, 3176, 7570 }
	end
end
do
	local player = players["neverontime"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9168, 172, 360, 11663 }
	end
end
do
	local player = players["overfarm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4691, 32, 44, 118 }
	end
end
do
	local player = players["yoshiisan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4583, 1226, 2543, 8284 }
	end
end
do
	local player = players["roguespike"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5187, 48, 88, 6299 }
	end
end
do
	local player = players["enotik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8920, 282, 559, 11114 }
	end
end
do
	local player = players["hawbee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4113, 1872, 4555, 7080 }
	end
end
do
	local player = players["getdavoodoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6756, 748, 1650, 9845 }
	end
end
do
	local player = players["rhersthestab"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8553, 360, 749, 10834 }
	end
end
do
	local player = players["sukensin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3276, 2013, 4950, 5640 }
	end
end
do
	local player = players["kuzatora"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6378, 851, 1873, 9697 }
	end
end
do
	local player = players["venomist"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6691, 768, 1695, 9826 }
	end
end
do
	local player = players["hykaroz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7822, 522, 1116, 10379 }
	end
end
do
	local player = players["pedror"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4693, 1589, 3755, 8080 }
	end
end
do
	local player = players["rakrom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7840, 514, 1095, 10387 }
	end
end
do
	local player = players["cutey"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4024, 1900, 4643, 6928 }
	end
end
do
	local player = players["furyrog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9015, 251, 502, 11199 }
	end
end
do
	local player = players["dorsa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8836, 298, 597, 11042 }
	end
end
do
	local player = players["goosex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9654, 97, 180, 12113 }
	end
end
do
	local player = players["slitrog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9554, 116, 226, 11845 }
	end
end
do
	local player = players["sneakystef"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4960, 1433, 3321, 8539 }
	end
end
do
	local player = players["varjoina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5318, 1144, 2566, 9155 }
	end
end
do
	local player = players["chjamja"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8500, 376, 776, 10802 }
	end
end
do
	local player = players["nedati"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4762, 1585, 3727, 8198 }
	end
end
do
	local player = players["bubbon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8353, 406, 852, 10698 }
	end
end
do
	local player = players["huh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6757, 761, 1677, 9858 }
	end
end
do
	local player = players["pabloescoba"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6196, 895, 1967, 9629 }
	end
end
do
	local player = players["kaulitsos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3664, 1980, 4869, 6308 }
	end
end
do
	local player = players["koaluss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9207, 200, 411, 11396 }
	end
end
do
	local player = players["mercx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5724, 1003, 2211, 9451 }
	end
end
do
	local player = players["lencselul"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9286, 178, 370, 11492 }
	end
end
do
	local player = players["payroll"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5033, 1388, 3207, 8664 }
	end
end
do
	local player = players["waduhek"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9429, 144, 296, 11669 }
	end
end
do
	local player = players["riddic"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8580, 353, 735, 10859 }
	end
end
do
	local player = players["nagibashka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8140, 453, 962, 10560 }
	end
end
do
	local player = players["qunncy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4698, 1614, 3820, 8087 }
	end
end
do
	local player = players["viancagodshi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6503, 818, 1808, 9742 }
	end
end
do
	local player = players["tramontina"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9630, 99, 192, 12076 }
	end
end
do
	local player = players["nukka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5255, 1199, 2706, 9047 }
	end
end
do
	local player = players["tynext"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7053, 697, 1524, 9986 }
	end
end
do
	local player = players["razialust"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2301, 478, 928, 8 }
	end
end
do
	local player = players["defocused"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4069, 390, 727, 22 }
	end
end
do
	local player = players["shamanpax"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 377, 592, 1151, 0 }
	end
end
do
	local player = players["whathero"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5732, 287, 511, 39 }
	end
end
do
	local player = players["bokluche"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5381, 308, 553, 35 }
	end
end
do
	local player = players["aoyina"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2623, 471, 904, 10 }
	end
end
do
	local player = players["nayrre"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 776, 576, 1130, 1 }
	end
end
do
	local player = players["estimated"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 556, 589, 1157, 0 }
	end
end
do
	local player = players["hatabich"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7157, 205, 349, 66 }
	end
end
do
	local player = players["badnet"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 449, 594, 1170, 0 }
	end
end
do
	local player = players["barryi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3529, 423, 793, 17 }
	end
end
do
	local player = players["iwoshamy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7623, 179, 292, 78 }
	end
end
do
	local player = players["trinyty"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 1471, 539, 1045, 3 }
	end
end
do
	local player = players["taliven"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4166, 1099, 2178, 6995 }
	end
end
do
	local player = players["afflidance"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6007, 115, 252, 9799 }
	end
end
do
	local player = players["melisandrei"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6367, 92, 195, 10385 }
	end
end
do
	local player = players["estoppel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4546, 977, 1896, 7633 }
	end
end
do
	local player = players["xplorer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5496, 158, 351, 8964 }
	end
end
do
	local player = players["oblepih"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4505, 199, 438, 7348 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4248, 1075, 2130, 7133 }
	end
end
do
	local player = players["shadowgamer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3765, 1176, 2364, 6321 }
	end
end
do
	local player = players["crxsser"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3859, 1161, 2333, 6480 }
	end
end
do
	local player = players["unfeasible"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6877, 452, 806, 9399 }
	end
end
do
	local player = players["behemoth"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9352, 97, 168, 11155 }
	end
end
do
	local player = players["lider"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8945, 157, 273, 10677 }
	end
end
do
	local player = players["serfas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3820, 1168, 2346, 6413 }
	end
end
do
	local player = players["kynvx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4900, 810, 1525, 8227 }
	end
end
do
	local player = players["fearlessfury"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9263, 112, 191, 11021 }
	end
end
do
	local player = players["chantel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3838, 1163, 2337, 6444 }
	end
end
do
	local player = players["chaoswave"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7219, 400, 718, 9582 }
	end
end
do
	local player = players["seandots"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5021, 752, 1396, 8430 }
	end
end
do
	local player = players["hellkiss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4538, 986, 1910, 7620 }
	end
end
do
	local player = players["harambex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5946, 567, 1046, 8994 }
	end
end
do
	local player = players["bladderburst"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8126, 277, 484, 10080 }
	end
end
do
	local player = players["mudalizem"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4915, 186, 415, 8018 }
	end
end
do
	local player = players["summonr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7184, 408, 727, 9566 }
	end
end
do
	local player = players["brujillizas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7591, 347, 622, 9782 }
	end
end
do
	local player = players["cuchulaine"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8379, 239, 419, 10250 }
	end
end
do
	local player = players["roxhy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4861, 832, 1568, 8162 }
	end
end
do
	local player = players["rasputyn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7995, 294, 518, 9991 }
	end
end
do
	local player = players["deffnotgay"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8600, 206, 362, 10434 }
	end
end
do
	local player = players["itwontfitdad"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6328, 96, 203, 10322 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5107, 703, 1288, 8575 }
	end
end
do
	local player = players["warology"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2866, 216, 469, 4674 }
	end
end
do
	local player = players["zeaquiem"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5609, 618, 1133, 8835 }
	end
end
do
	local player = players["bahtiujasa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7669, 333, 602, 9808 }
	end
end
do
	local player = players["vpmdemon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5020, 753, 1397, 8429 }
	end
end
do
	local player = players["warjaack"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4843, 847, 1593, 8132 }
	end
end
do
	local player = players["aguadecalzon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4232, 1086, 2146, 7106 }
	end
end
do
	local player = players["ihgtn"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5957, 117, 262, 9717 }
	end
end
do
	local player = players["krobeluss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6959, 440, 785, 9441 }
	end
end
do
	local player = players["iskariote"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3810, 1169, 2348, 6397 }
	end
end
do
	local player = players["zlosynus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2843, 1252, 2522, 4774 }
	end
end
do
	local player = players["evercolder"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2667, 3030, 8170, 6729 }
	end
end
do
	local player = players["tacttus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4958, 1820, 4307, 10327 }
	end
end
do
	local player = players["drokos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7926, 854, 1772, 12160 }
	end
end
do
	local player = players["kurozackzx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4828, 1853, 4418, 10261 }
	end
end
do
	local player = players["muflord"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6983, 1160, 2578, 11501 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7059, 31, 112, 2323 }
	end
end
do
	local player = players["drexort"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8094, 798, 1629, 12299 }
	end
end
do
	local player = players["chjam"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9191, 400, 692, 13476 }
	end
end
do
	local player = players["draztikx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8114, 792, 1612, 12311 }
	end
end
do
	local player = players["yfrex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5901, 1515, 3502, 10847 }
	end
end
do
	local player = players["ravaszz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5832, 1539, 3561, 10812 }
	end
end
do
	local player = players["sharthe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5196, 1742, 4104, 10456 }
	end
end
do
	local player = players["madmadlad"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7473, 1003, 2159, 11815 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5980, 42, 130, 2095 }
	end
end
do
	local player = players["vimaranes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4809, 1859, 4435, 10255 }
	end
end
do
	local player = players["otiv"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3306, 2727, 7145, 8344 }
	end
end
do
	local player = players["clypclap"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6642, 1269, 2869, 11269 }
	end
end
do
	local player = players["orokai"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3654, 2390, 6019, 9222 }
	end
end
do
	local player = players["cleavko"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3210, 2791, 7369, 8102 }
	end
end
do
	local player = players["bundes"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3463, 2590, 6665, 8739 }
	end
end
do
	local player = players["vodkaftw"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5886, 1522, 3515, 10836 }
	end
end
do
	local player = players["killersx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7460, 1009, 2170, 11808 }
	end
end
do
	local player = players["zurgohg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3290, 2737, 7188, 8304 }
	end
end
do
	local player = players["ceckawar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8183, 771, 1553, 12365 }
	end
end
do
	local player = players["huug"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4735, 1881, 4498, 10223 }
	end
end
do
	local player = players["chichioh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8481, 669, 1298, 12646 }
	end
end
do
	local player = players["selyely"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5066, 1787, 4215, 10383 }
	end
end
do
	local player = players["rendsabandon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3558, 2501, 6358, 8979 }
	end
end
do
	local player = players["warvole"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5276, 1707, 4036, 10501 }
	end
end
do
	local player = players["lihua"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8769, 560, 1052, 12931 }
	end
end
do
	local player = players["zbekoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3837, 2182, 5357, 9683 }
	end
end
do
	local player = players["bloodbrawl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9156, 414, 722, 13434 }
	end
end
do
	local player = players["moywarrior"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3693, 2343, 5882, 9319 }
	end
end
do
	local player = players["tinycow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3680, 2358, 5924, 9287 }
	end
end
do
	local player = players["verystrong"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5791, 1549, 3596, 10790 }
	end
end
do
	local player = players["mamulski"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7795, 884, 1884, 12082 }
	end
end
do
	local player = players["marrowgar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6055, 1468, 3370, 10923 }
	end
end
do
	local player = players["sodiw"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8066, 805, 1653, 12275 }
	end
end
do
	local player = players["sansol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3694, 2341, 5876, 9323 }
	end
end
do
	local player = players["googleit"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8390, 699, 1376, 12551 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9020, 11, 78, 3281 }
	end
end
do
	local player = players["amko"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3618, 2439, 6154, 9130 }
	end
end
do
	local player = players["warrioraa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6073, 1464, 3355, 10932 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4901, 54, 156, 1280 }
	end
end
do
	local player = players["awarfurry"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3702, 2337, 5860, 9342 }
	end
end
do
	local player = players["setuppwar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3049, 2886, 7736, 7696 }
	end
end
do
	local player = players["kynux"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3815, 2211, 5448, 9629 }
	end
end
do
	local player = players["ojusticeiro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4754, 1876, 4482, 10231 }
	end
end
do
	local player = players["iamprot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5403, 1668, 3927, 10577 }
	end
end
do
	local player = players["okun"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3658, 2384, 6003, 9232 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
