-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "rs"
local chunkStartIndex = 32563
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["sigurito"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9283, 421, 1169, 2859 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2938, 1118, 4464, 2262 }
	end
end
do
	local player = players["tankiliasx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8184, 1250, 4555, 2580 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1065, 1259, 5648, 1611 }
	end
end
do
	local player = players["tsinish"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9263, 444, 1220, 2839 }
	end
end
do
	local player = players["veekyung"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8562, 993, 3297, 2649 }
	end
end
do
	local player = players["itsnobody"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8946, 688, 2017, 2758 }
	end
end
do
	local player = players["kappew"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2441, 1072, 4376, 2215 }
	end
end
do
	local player = players["bolszewik"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9446, 289, 810, 2932 }
	end
end
do
	local player = players["resurrected"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8666, 921, 2949, 2680 }
	end
end
do
	local player = players["bummbbleebe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8716, 880, 2785, 2693 }
	end
end
do
	local player = players["taureau"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8801, 806, 2500, 2707 }
	end
end
do
	local player = players["wraithknight"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7925, 1407, 5419, 2540 }
	end
end
do
	local player = players["diewithblood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9169, 529, 1455, 2817 }
	end
end
do
	local player = players["tempp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8589, 977, 3207, 2658 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1779, 1179, 5069, 2027 }
	end
end
do
	local player = players["xtragrip"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9171, 527, 1450, 2809 }
	end
end
do
	local player = players["tankiliasxc"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8413, 1588, 6562, 2473 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1685, 1134, 4838, 2041 }
	end
end
do
	local player = players["volzmir"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8315, 1173, 4119, 2599 }
	end
end
do
	local player = players["fadenight"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9295, 414, 1140, 2855 }
	end
end
do
	local player = players["tiodeyisus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9320, 387, 1078, 2867 }
	end
end
do
	local player = players["bigchoddy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7846, 1449, 5683, 2516 }
	end
end
do
	local player = players["buumblebee"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8803, 805, 2492, 2710 }
	end
end
do
	local player = players["confidk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7651, 1551, 6334, 2489 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7713, 2288, 9964, 9313 }
	end
end
do
	local player = players["kiasataa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8870, 757, 2271, 2736 }
	end
end
do
	local player = players["meanork"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8707, 1294, 4947, 2547 }
	end
end
do
	local player = players["muurcia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8588, 1413, 5518, 2521 }
	end
end
do
	local player = players["zorzbraun"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8677, 910, 2913, 2676 }
	end
end
do
	local player = players["stylishdk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7399, 1693, 7174, 2457 }
	end
end
do
	local player = players["insite"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8060, 1941, 9081, 2362 }
	end
end
do
	local player = players["mightydkk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8306, 1183, 4149, 2597 }
	end
end
do
	local player = players["plaguecleave"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9313, 393, 1095, 2862 }
	end
end
do
	local player = players["rolandc"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8960, 1041, 3629, 2619 }
	end
end
do
	local player = players["irental"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9474, 267, 753, 2961 }
	end
end
do
	local player = players["laowudk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8676, 909, 2917, 2672 }
	end
end
do
	local player = players["whosthetank"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6897, 625, 1863, 8183 }
	end
end
do
	local player = players["yultuchiha"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7858, 1451, 5643, 2526 }
	end
end
do
	local player = players["anakhorg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8352, 1142, 3997, 2604 }
	end
end
do
	local player = players["ongh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9394, 607, 1718, 2774 }
	end
end
do
	local player = players["shekespeare"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8575, 988, 3253, 2654 }
	end
end
do
	local player = players["elrobusto"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9292, 709, 2096, 2740 }
	end
end
do
	local player = players["pongniyan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8075, 1316, 4920, 2564 }
	end
end
do
	local player = players["rampie"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8502, 1034, 3498, 2635 }
	end
end
do
	local player = players["thelastblood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7717, 1523, 6113, 2498 }
	end
end
do
	local player = players["zorra"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8295, 1706, 7524, 2428 }
	end
end
do
	local player = players["alfadeath"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7999, 1355, 5174, 2541 }
	end
end
do
	local player = players["banzuke"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8467, 1534, 6313, 2481 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7918, 2083, 8844, 9503 }
	end
end
do
	local player = players["coffinz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9172, 829, 2599, 2695 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3148, 1009, 3987, 2409 }
	end
end
do
	local player = players["dranzsavior"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9129, 570, 1555, 2797 }
	end
end
do
	local player = players["meruh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8254, 1206, 4325, 2586 }
	end
end
do
	local player = players["uppercut"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7557, 1614, 6646, 2480 }
	end
end
do
	local player = players["zomia"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7981, 1366, 5232, 2549 }
	end
end
do
	local player = players["gzorenlelg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8339, 1156, 4039, 2604 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7831, 472, 1322, 10324 }
	end
end
do
	local player = players["pockdk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9520, 481, 1332, 2820 }
	end
end
do
	local player = players["unpredicted"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9101, 590, 1625, 2795 }
	end
end
do
	local player = players["tonsoffun"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6673, 2027, 9594, 2358 }
	end
end
do
	local player = players["emstoppable"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9593, 408, 1138, 2846 }
	end
end
do
	local player = players["dedork"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9112, 580, 1597, 2798 }
	end
end
do
	local player = players["toxicgirla"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7606, 529, 1514, 9874 }
	end
end
do
	local player = players["ulzac"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6879, 1936, 8908, 2387 }
	end
end
do
	local player = players["hanziedekl"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8019, 1345, 5108, 2549 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5795, 721, 2562, 5245 }
	end
end
do
	local player = players["danidk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7884, 1431, 5555, 2533 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2059, 1180, 5020, 2084 }
	end
end
do
	local player = players["vylizprdel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7396, 1692, 7182, 2460 }
	end
end
do
	local player = players["beringe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9476, 251, 750, 11709 }
	end
end
do
	local player = players["frozenffs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6972, 637, 1915, 7985 }
	end
end
do
	local player = players["linkos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9293, 188, 448, 12101 }
	end
end
do
	local player = players["deathhshik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6375, 697, 2292, 5603 }
	end
end
do
	local player = players["dins"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9386, 164, 389, 12197 }
	end
end
do
	local player = players["nirvik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5511, 756, 2838, 4843 }
	end
end
do
	local player = players["steezy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9487, 136, 325, 12342 }
	end
end
do
	local player = players["qxldk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5267, 779, 2992, 4583 }
	end
end
do
	local player = players["nightmaretwo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7133, 602, 1813, 8688 }
	end
end
do
	local player = players["putridpile"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6945, 640, 1932, 7812 }
	end
end
do
	local player = players["kilian"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7631, 525, 1498, 9915 }
	end
end
do
	local player = players["joelyne"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5340, 754, 2874, 4751 }
	end
end
do
	local player = players["obiuan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9807, 54, 123, 13140 }
	end
end
do
	local player = players["blackplague"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6597, 2057, 9846, 2344 }
	end
end
do
	local player = players["dkartman"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8945, 258, 639, 11685 }
	end
end
do
	local player = players["stocks"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6559, 2308, 9973, 9389 }
	end
end
do
	local player = players["pestylence"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6672, 2226, 9595, 9452 }
	end
end
do
	local player = players["saigilia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7962, 1416, 5295, 10208 }
	end
end
do
	local player = players["blazingfast"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8425, 1086, 3754, 2626 }
	end
end
do
	local player = players["notcloudy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8776, 1225, 4374, 10387 }
	end
end
do
	local player = players["nathanos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9687, 314, 920, 11558 }
	end
end
do
	local player = players["nazgrrim"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7046, 2011, 8350, 9635 }
	end
end
do
	local player = players["nbj"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8823, 748, 2427, 10940 }
	end
end
do
	local player = players["reboke"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7314, 1845, 7456, 9835 }
	end
end
do
	local player = players["sniclica"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8003, 1389, 5160, 10235 }
	end
end
do
	local player = players["azerusftw"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8130, 1296, 4738, 10368 }
	end
end
do
	local player = players["gonzadk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7955, 1389, 5321, 2544 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8042, 1348, 5031, 10308 }
	end
end
do
	local player = players["hestiadps"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8812, 1189, 4241, 10419 }
	end
end
do
	local player = players["juewushen"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7509, 1721, 6807, 9933 }
	end
end
do
	local player = players["smoke"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9377, 624, 1960, 11066 }
	end
end
do
	local player = players["zankai"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9122, 506, 1573, 11240 }
	end
end
do
	local player = players["bringerdeath"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7023, 2033, 8428, 9634 }
	end
end
do
	local player = players["forzah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8122, 1879, 7667, 9721 }
	end
end
do
	local player = players["honnored"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8809, 755, 2472, 10921 }
	end
end
do
	local player = players["luxage"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7142, 1956, 8031, 9741 }
	end
end
do
	local player = players["yultnotopea"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7813, 2188, 9332, 9424 }
	end
end
do
	local player = players["ayarmanco"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7872, 1443, 5596, 2531 }
	end
end
do
	local player = players["ghosstt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8879, 1122, 3970, 10477 }
	end
end
do
	local player = players["mjs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8260, 1741, 6905, 9875 }
	end
end
do
	local player = players["nightmoon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9965, 11, 36, 14031 }
	end
end
do
	local player = players["thelete"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7920, 1442, 5437, 10193 }
	end
end
do
	local player = players["yamilazo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8140, 1861, 7515, 9751 }
	end
end
do
	local player = players["hellzdude"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7221, 1904, 7768, 9785 }
	end
end
do
	local player = players["mykjones"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9210, 445, 1353, 11329 }
	end
end
do
	local player = players["sarykum"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8375, 1105, 3920, 10530 }
	end
end
do
	local player = players["stearin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9392, 308, 919, 11578 }
	end
end
do
	local player = players["frostdigger"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8404, 1076, 3822, 10572 }
	end
end
do
	local player = players["scaythe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9168, 212, 527, 11948 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8082, 1327, 4895, 10334 }
	end
end
do
	local player = players["icybuba"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9054, 540, 1742, 11210 }
	end
end
do
	local player = players["mblwka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9245, 458, 1264, 2841 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9937, 19, 64, 13681 }
	end
end
do
	local player = players["ignore"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6601, 2054, 9833, 2348 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8042, 1347, 5030, 10308 }
	end
end
do
	local player = players["galekrim"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7629, 1639, 6408, 10026 }
	end
end
do
	local player = players["avija"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8170, 1266, 4604, 10395 }
	end
end
do
	local player = players["necroface"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9956, 13, 45, 14032 }
	end
end
do
	local player = players["pockxx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9415, 307, 872, 2925 }
	end
end
do
	local player = players["aiaia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8586, 940, 3216, 10684 }
	end
end
do
	local player = players["bowann"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7932, 1403, 5398, 2533 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8725, 830, 2752, 10826 }
	end
end
do
	local player = players["lireid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9173, 523, 1444, 2818 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8201, 1244, 4501, 10417 }
	end
end
do
	local player = players["drizl"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8630, 902, 3071, 10761 }
	end
end
do
	local player = players["iraniantank"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8034, 1337, 5057, 2557 }
	end
end
do
	local player = players["kortaa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8831, 785, 2399, 2725 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7866, 1474, 5616, 10191 }
	end
end
do
	local player = players["moydkuh"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8292, 1165, 4196, 10478 }
	end
end
do
	local player = players["wrecklessnes"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8392, 1085, 3863, 10561 }
	end
end
do
	local player = players["ninosodomia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5886, 729, 2601, 5214 }
	end
end
do
	local player = players["dkpredator"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8948, 620, 2011, 11103 }
	end
end
do
	local player = players["gortzak"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8948, 685, 2011, 2758 }
	end
end
do
	local player = players["kaalgarona"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8936, 634, 2051, 11091 }
	end
end
do
	local player = players["dreizer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8395, 1081, 3853, 10564 }
	end
end
do
	local player = players["maksidan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7924, 465, 1313, 10378 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6820, 2132, 9104, 9543 }
	end
end
do
	local player = players["zmishi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7399, 1786, 7173, 9889 }
	end
end
do
	local player = players["elzaan"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8063, 1318, 4960, 2554 }
	end
end
do
	local player = players["colldknight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5797, 734, 2657, 5125 }
	end
end
do
	local player = players["lichkingsoul"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7676, 516, 1470, 9996 }
	end
end
do
	local player = players["uerbainner"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8549, 1007, 3340, 2652 }
	end
end
do
	local player = players["proginy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8150, 422, 1170, 10701 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7208, 1915, 7809, 9777 }
	end
end
do
	local player = players["brygadadk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7413, 1774, 7128, 9897 }
	end
end
do
	local player = players["hausenberg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7470, 1658, 6937, 2471 }
	end
end
do
	local player = players["devilenight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8285, 392, 1085, 10867 }
	end
end
do
	local player = players["doomjack"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9516, 218, 671, 11835 }
	end
end
do
	local player = players["tabiti"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7428, 1764, 7077, 9903 }
	end
end
do
	local player = players["amonrah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7956, 1412, 5317, 10249 }
	end
end
do
	local player = players["scapychyr"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7260, 1882, 7638, 9805 }
	end
end
do
	local player = players["ovie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6634, 2257, 9724, 9432 }
	end
end
do
	local player = players["loyren"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7401, 1783, 7168, 9889 }
	end
end
do
	local player = players["eldruid"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6966, 1914, 8618, 9535 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3685, 1000, 4279, 7 }
	end
end
do
	local player = players["tifonenelano"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5504, 740, 2996, 17 }
	end
end
do
	local player = players["hardfisting"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2193, 1236, 5322, 2 }
	end
end
do
	local player = players["mythanexd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5544, 735, 2969, 18 }
	end
end
do
	local player = players["srunezametno"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4225, 915, 3848, 10 }
	end
end
do
	local player = players["lustello"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8772, 258, 819, 62 }
	end
end
do
	local player = players["amayah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3028, 1104, 4806, 4 }
	end
end
do
	local player = players["riffraff"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5514, 739, 2989, 17 }
	end
end
do
	local player = players["gitguud"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6693, 2068, 9528, 9424 }
	end
end
do
	local player = players["sovywka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8648, 828, 3010, 10517 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9070, 554, 1702, 13514 }
	end
end
do
	local player = players["dreamberry"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2623, 1168, 5076, 3 }
	end
end
do
	local player = players["whitetank"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 280, 1496, 6235, 0 }
	end
end
do
	local player = players["mahkah"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 695, 1473, 6341, 0 }
	end
end
do
	local player = players["cowdoesmoo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6896, 1954, 8851, 9506 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2092, 1252, 5392, 2 }
	end
end
do
	local player = players["sikayu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8320, 345, 1120, 52 }
	end
end
do
	local player = players["skarllet"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6564, 594, 2290, 26 }
	end
end
do
	local player = players["dyfrex"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2472, 1192, 5161, 3 }
	end
end
do
	local player = players["thickbird"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6410, 614, 2392, 24 }
	end
end
do
	local player = players["doublledude"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4429, 886, 3712, 11 }
	end
end
do
	local player = players["sacrilegio"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7354, 1678, 7322, 9707 }
	end
end
do
	local player = players["onnechance"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2118, 1248, 5377, 2 }
	end
end
do
	local player = players["kovbassa"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3034, 1103, 4804, 4 }
	end
end
do
	local player = players["elderone"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7786, 432, 1476, 41 }
	end
end
do
	local player = players["ugnele"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2364, 1209, 5214, 2 }
	end
end
do
	local player = players["kaidx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 575, 1492, 6391, 0 }
	end
end
do
	local player = players["telepatia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9248, 173, 502, 83 }
	end
end
do
	local player = players["flamingo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 411, 1518, 6456, 0 }
	end
end
do
	local player = players["forestling"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3407, 1044, 4482, 6 }
	end
end
do
	local player = players["tindarey"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7084, 1845, 8224, 9548 }
	end
end
do
	local player = players["entonio"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8516, 917, 3449, 10395 }
	end
end
do
	local player = players["astaya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1628, 1312, 5663, 1 }
	end
end
do
	local player = players["druidotmkd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3755, 989, 4247, 7 }
	end
end
do
	local player = players["tannin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2933, 1119, 4885, 4 }
	end
end
do
	local player = players["payperheal"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2630, 1153, 4986, 3 }
	end
end
do
	local player = players["tiridowl"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7391, 1659, 7201, 9725 }
	end
end
do
	local player = players["imuniz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4185, 921, 3893, 9 }
	end
end
do
	local player = players["whoasked"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3698, 998, 4276, 7 }
	end
end
do
	local player = players["tobibear"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 841, 1450, 6285, 0 }
	end
end
do
	local player = players["jeckiechan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7699, 1427, 6174, 12269 }
	end
end
do
	local player = players["adelmiau"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9100, 538, 1628, 13518 }
	end
end
do
	local player = players["alorrdish"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7123, 1747, 8092, 11904 }
	end
end
do
	local player = players["ayecantdie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9739, 262, 664, 14025 }
	end
end
do
	local player = players["bartan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9571, 430, 1254, 13679 }
	end
end
do
	local player = players["floresth"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8709, 812, 2808, 13127 }
	end
end
do
	local player = players["shredferal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9120, 522, 1577, 13533 }
	end
end
do
	local player = players["erniex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7927, 1293, 5412, 12471 }
	end
end
do
	local player = players["gremdar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6289, 2406, 12617, 10371 }
	end
end
do
	local player = players["mixet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9988, 13, 22, 15958 }
	end
end
do
	local player = players["pulefa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9006, 592, 1863, 13434 }
	end
end
do
	local player = players["barstronk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9723, 278, 723, 13976 }
	end
end
do
	local player = players["bulcyngier"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7952, 1280, 5330, 12493 }
	end
end
do
	local player = players["matambrito"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9360, 641, 2074, 13329 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8765, 254, 789, 62 }
	end
end
do
	local player = players["narkomaniya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8818, 740, 2444, 13231 }
	end
end
do
	local player = players["insecure"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7572, 1489, 6595, 12196 }
	end
end
do
	local player = players["neekita"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8789, 1212, 4864, 12558 }
	end
end
do
	local player = players["treemaokai"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 237, 1527, 6429, 0 }
	end
end
do
	local player = players["waitnbleed"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9879, 122, 271, 14467 }
	end
end
do
	local player = players["dudurager"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8227, 1123, 4412, 12701 }
	end
end
do
	local player = players["feral"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8658, 846, 2978, 13084 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2720, 1141, 4978, 3 }
	end
end
do
	local player = players["mostachini"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9332, 669, 2142, 13305 }
	end
end
do
	local player = players["myravei"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9703, 298, 779, 13930 }
	end
end
do
	local player = players["pasteurorist"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8556, 1445, 6252, 12241 }
	end
end
do
	local player = players["pokusemta"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8100, 1203, 4836, 12602 }
	end
end
do
	local player = players["futtbuckerx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8364, 1030, 3956, 12845 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7440, 478, 1706, 36 }
	end
end
do
	local player = players["anzu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8743, 265, 838, 61 }
	end
end
do
	local player = players["yavvru"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 1226, 1389, 6050, 1 }
	end
end
do
	local player = players["strovaljivac"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7758, 1406, 5977, 12376 }
	end
end
do
	local player = players["kravicka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7356, 1676, 7315, 9708 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8613, 295, 925, 58 }
	end
end
do
	local player = players["gatacat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8124, 1189, 4758, 12647 }
	end
end
do
	local player = players["caanix"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8430, 327, 1047, 54 }
	end
end
do
	local player = players["codru"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8254, 1115, 4323, 12755 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9442, 131, 373, 97 }
	end
end
do
	local player = players["lohil"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8259, 1108, 4305, 12760 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7373, 488, 1751, 35 }
	end
end
do
	local player = players["usoopp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9710, 143, 330, 14418 }
	end
end
do
	local player = players["thastordj"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8022, 1252, 5095, 12573 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8916, 236, 723, 67 }
	end
end
do
	local player = players["kokoszi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7047, 1788, 8348, 11844 }
	end
end
do
	local player = players["sensii"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8571, 901, 3265, 13014 }
	end
end
do
	local player = players["juicypear"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6922, 1849, 8763, 11743 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5890, 687, 2739, 20 }
	end
end
do
	local player = players["mitsudruid"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7233, 1686, 7726, 11984 }
	end
end
do
	local player = players["malleabull"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6780, 1917, 9235, 11632 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2705, 1155, 5034, 3 }
	end
end
do
	local player = players["feralistical"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8219, 1131, 4440, 12680 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 834, 1418, 6078, 0 }
	end
end
do
	local player = players["tiernan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7863, 1336, 5628, 12453 }
	end
end
do
	local player = players["zhozho"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8266, 1103, 4282, 12764 }
	end
end
do
	local player = players["nugyen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7982, 1271, 5230, 12545 }
	end
end
do
	local player = players["malarius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8128, 1181, 4743, 12650 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9066, 210, 623, 73 }
	end
end
do
	local player = players["jolian"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8229, 1127, 4405, 12733 }
	end
end
do
	local player = players["mihoo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 958, 1388, 5936, 0 }
	end
end
do
	local player = players["digbickk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7889, 1321, 5539, 12476 }
	end
end
do
	local player = players["nabdudu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7802, 1373, 5829, 12406 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9041, 215, 640, 72 }
	end
end
do
	local player = players["scuffeddruid"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7431, 480, 1712, 36 }
	end
end
do
	local player = players["albutheghost"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6563, 2039, 9959, 11427 }
	end
end
do
	local player = players["coolphone"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7203, 1703, 7827, 11960 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4606, 863, 3594, 12 }
	end
end
do
	local player = players["evilgrand"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4311, 876, 3639, 10 }
	end
end
do
	local player = players["lesleyss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8628, 865, 3077, 13067 }
	end
end
do
	local player = players["ziivert"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8544, 918, 3357, 12990 }
	end
end
do
	local player = players["smashcat"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5789, 700, 2806, 19 }
	end
end
do
	local player = players["innari"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7565, 457, 1623, 38 }
	end
end
do
	local player = players["kitkudi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7098, 1761, 8176, 11886 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2307, 1218, 5249, 2 }
	end
end
do
	local player = players["kixx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9387, 142, 409, 93 }
	end
end
do
	local player = players["mezgapre"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8040, 1241, 5035, 12583 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9186, 181, 543, 80 }
	end
end
do
	local player = players["noobpaladudu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 556, 1495, 6397, 0 }
	end
end
do
	local player = players["skuchid"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3394, 1046, 4488, 6 }
	end
end
do
	local player = players["shuainiuxd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3951, 958, 4067, 8 }
	end
end
do
	local player = players["okounaator"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6582, 2026, 9895, 11413 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9827, 49, 116, 155 }
	end
end
do
	local player = players["xarambe"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7091, 1762, 8201, 11880 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9977, 16, 16, 305 }
	end
end
do
	local player = players["etalonis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3527, 1025, 4386, 6 }
	end
end
do
	local player = players["admarantt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5056, 800, 3294, 14 }
	end
end
do
	local player = players["saltedveggie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8263, 355, 1158, 50 }
	end
end
do
	local player = players["drbanana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4121, 931, 3928, 9 }
	end
end
do
	local player = players["chowder"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7251, 503, 1832, 33 }
	end
end
do
	local player = players["savosaren"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5118, 794, 3253, 15 }
	end
end
do
	local player = players["aoich"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 613, 1486, 6374, 0 }
	end
end
do
	local player = players["qgolkekw"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2178, 1226, 5275, 2 }
	end
end
do
	local player = players["kurizalf"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5318, 751, 3039, 16 }
	end
end
do
	local player = players["logansdruid"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3647, 1006, 4317, 7 }
	end
end
do
	local player = players["bestiakodo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9075, 205, 617, 74 }
	end
end
do
	local player = players["manadge"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 3155, 1073, 4639, 5 }
	end
end
do
	local player = players["verdinhocat"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2737, 1150, 5014, 3 }
	end
end
do
	local player = players["ogdudus"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2412, 1187, 5095, 2 }
	end
end
do
	local player = players["hotchiick"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4402, 862, 3601, 10 }
	end
end
do
	local player = players["cervixpunchr"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5293, 39, 157, 5774 }
	end
end
do
	local player = players["umaru"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 11, 78, 344, 21 }
	end
end
do
	local player = players["saplar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9586, 297, 530, 342 }
	end
end
do
	local player = players["deepanddark"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7855, 1851, 5653, 241 }
	end
end
do
	local player = players["ggcup"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7535, 2059, 6720, 233 }
	end
end
do
	local player = players["seniness"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6903, 2488, 8825, 219 }
	end
end
do
	local player = players["talewinter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8998, 836, 1883, 291 }
	end
end
do
	local player = players["breakspear"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8829, 1026, 2406, 281 }
	end
end
do
	local player = players["plsnotme"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8990, 841, 1903, 290 }
	end
end
do
	local player = players["johnnytaco"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9217, 645, 1334, 305 }
	end
end
do
	local player = players["pirsaholy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9272, 585, 1198, 310 }
	end
end
do
	local player = players["franeks"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6938, 2460, 8709, 219 }
	end
end
do
	local player = players["adepala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6929, 2467, 8739, 219 }
	end
end
do
	local player = players["marmeladova"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7839, 1864, 5705, 241 }
	end
end
do
	local player = players["ilargi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8493, 1349, 3526, 264 }
	end
end
do
	local player = players["sqar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9153, 702, 1496, 300 }
	end
end
do
	local player = players["jaca"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8764, 1096, 2623, 277 }
	end
end
do
	local player = players["hencai"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8663, 1204, 2960, 271 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7543, 1552, 6693, 1681 }
	end
end
do
	local player = players["corbeil"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9213, 649, 1346, 305 }
	end
end
do
	local player = players["palaili"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9281, 577, 1174, 310 }
	end
end
do
	local player = players["hollya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9434, 444, 833, 325 }
	end
end
do
	local player = players["palalaura"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8274, 1543, 4255, 255 }
	end
end
do
	local player = players["dov"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9081, 769, 1676, 296 }
	end
end
do
	local player = players["tauntahora"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9130, 725, 1553, 299 }
	end
end
do
	local player = players["spurdo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6617, 2643, 9780, 213 }
	end
end
do
	local player = players["sakollik"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8065, 1693, 4953, 247 }
	end
end
do
	local player = players["valxalla"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9324, 535, 1068, 314 }
	end
end
do
	local player = players["ingredient"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8782, 1069, 2562, 278 }
	end
end
do
	local player = players["canthealaids"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8764, 1095, 2622, 277 }
	end
end
do
	local player = players["roflapplepie"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6978, 2432, 8578, 220 }
	end
end
do
	local player = players["luviena"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8747, 1118, 2679, 274 }
	end
end
do
	local player = players["likka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8272, 1538, 4264, 253 }
	end
end
do
	local player = players["binitin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8057, 1704, 4979, 247 }
	end
end
do
	local player = players["vikkadog"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7333, 2207, 7394, 227 }
	end
end
do
	local player = players["breathe"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8215, 1786, 5395, 241 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8946, 1055, 3306, 11694 }
	end
end
do
	local player = players["illumination"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9504, 375, 694, 330 }
	end
end
do
	local player = players["beldarana"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8726, 1139, 2749, 273 }
	end
end
do
	local player = players["indraa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8301, 1519, 4167, 255 }
	end
end
do
	local player = players["nhezy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7572, 2040, 6595, 234 }
	end
end
do
	local player = players["ponp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8544, 1302, 3355, 264 }
	end
end
do
	local player = players["lovely"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9707, 294, 590, 12532 }
	end
end
do
	local player = players["zoomspeed"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7704, 1960, 6157, 236 }
	end
end
do
	local player = players["aoqva"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9742, 160, 286, 367 }
	end
end
do
	local player = players["nashetania"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8107, 1666, 4812, 249 }
	end
end
do
	local player = players["ronnypally"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9037, 964, 2204, 282 }
	end
end
do
	local player = players["discopaladin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8029, 1972, 6328, 233 }
	end
end
do
	local player = players["iziproto"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8988, 1013, 2386, 278 }
	end
end
do
	local player = players["mystical"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7672, 2329, 8107, 221 }
	end
end
do
	local player = players["sariah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8313, 1507, 4126, 256 }
	end
end
do
	local player = players["applebutter"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8840, 1161, 2847, 270 }
	end
end
do
	local player = players["asjkghdasjkh"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8652, 1349, 3546, 261 }
	end
end
do
	local player = players["chiwa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7853, 1847, 5660, 240 }
	end
end
do
	local player = players["plaku"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8905, 941, 2153, 283 }
	end
end
do
	local player = players["pupeczka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8992, 840, 1898, 289 }
	end
end
do
	local player = players["vopi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7425, 2576, 9525, 212 }
	end
end
do
	local player = players["mostbrutal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8875, 976, 2253, 282 }
	end
end
do
	local player = players["nadxi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8189, 1602, 4541, 250 }
	end
end
do
	local player = players["paaceq"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7376, 2625, 9789, 210 }
	end
end
do
	local player = players["prostushka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9496, 380, 710, 330 }
	end
end
do
	local player = players["aalamierda"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6662, 2612, 9630, 214 }
	end
end
do
	local player = players["aviciixpala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8942, 884, 2029, 286 }
	end
end
do
	local player = players["neat"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8064, 1696, 4956, 248 }
	end
end
do
	local player = players["tessa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8892, 950, 2197, 284 }
	end
end
do
	local player = players["chkobba"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8430, 1401, 3738, 261 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7135, 1819, 8053, 1545 }
	end
end
do
	local player = players["mutafdategav"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7862, 1846, 5630, 241 }
	end
end
do
	local player = players["auragodx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9827, 73, 182, 3733 }
	end
end
do
	local player = players["twinlight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8903, 659, 2159, 2838 }
	end
end
do
	local player = players["dexterpally"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7580, 2037, 6569, 234 }
	end
end
do
	local player = players["lavalla"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8733, 1133, 2727, 274 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6893, 1937, 8861, 1475 }
	end
end
do
	local player = players["kacudo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8427, 1404, 3746, 261 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7485, 1595, 6888, 1658 }
	end
end
do
	local player = players["trunks"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7878, 1334, 5576, 1860 }
	end
end
do
	local player = players["oberona"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8315, 1064, 4119, 2271 }
	end
end
do
	local player = players["fogdmegjol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7020, 1873, 8436, 1517 }
	end
end
do
	local player = players["lendwik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8216, 1126, 4450, 2156 }
	end
end
do
	local player = players["chiitoge"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8937, 894, 2048, 287 }
	end
end
do
	local player = players["angkorpala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8014, 1245, 5122, 1964 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6828, 2317, 9075, 10919 }
	end
end
do
	local player = players["jonnythree"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9657, 167, 406, 3453 }
	end
end
do
	local player = players["yimikp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7585, 1521, 6552, 1699 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6686, 2503, 9963, 10793 }
	end
end
do
	local player = players["lightblade"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9409, 468, 884, 322 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8045, 1234, 5020, 1987 }
	end
end
do
	local player = players["pryimik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7581, 1524, 6566, 1696 }
	end
end
do
	local player = players["todpa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9272, 416, 1198, 3092 }
	end
end
do
	local player = players["moryena"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9496, 280, 711, 3276 }
	end
end
do
	local player = players["riso"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7842, 1358, 5698, 1837 }
	end
end
do
	local player = players["lipz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7904, 1316, 5490, 1877 }
	end
end
do
	local player = players["vurtex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9255, 432, 1241, 3075 }
	end
end
do
	local player = players["trytohelp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7971, 1274, 5265, 1933 }
	end
end
do
	local player = players["kenrin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7138, 1816, 8044, 1546 }
	end
end
do
	local player = players["crimsondemon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8303, 1074, 4161, 2257 }
	end
end
do
	local player = players["azinaara"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9290, 404, 1152, 3110 }
	end
end
do
	local player = players["stoneblooda"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7767, 1391, 5946, 1791 }
	end
end
do
	local player = players["vallien"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9502, 275, 699, 3282 }
	end
end
do
	local player = players["rbii"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6563, 2111, 9960, 1411 }
	end
end
do
	local player = players["naturalpal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6728, 2587, 9411, 216 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7273, 1724, 7592, 1591 }
	end
end
do
	local player = players["pikpalyfive"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9277, 411, 1184, 3096 }
	end
end
do
	local player = players["notirohop"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8650, 817, 3003, 2627 }
	end
end
do
	local player = players["votverpal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7352, 1676, 7329, 1613 }
	end
end
do
	local player = players["omniknight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7874, 1339, 5591, 1857 }
	end
end
do
	local player = players["aviciixblock"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9530, 471, 1399, 3014 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9155, 846, 2441, 11869 }
	end
end
do
	local player = players["legiatokurwa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8856, 689, 2317, 2790 }
	end
end
do
	local player = players["sryimik"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9147, 854, 2474, 11866 }
	end
end
do
	local player = players["mallusx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8957, 621, 1986, 2872 }
	end
end
do
	local player = players["notbetouch"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8632, 1369, 5826, 1777 }
	end
end
do
	local player = players["ankama"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8368, 1023, 3942, 2324 }
	end
end
do
	local player = players["nepwp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7748, 1419, 6009, 1762 }
	end
end
do
	local player = players["drainnae"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9464, 537, 1655, 2953 }
	end
end
do
	local player = players["happyend"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7780, 1385, 5903, 1801 }
	end
end
do
	local player = players["khoukh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9494, 282, 714, 3272 }
	end
end
do
	local player = players["trululut"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8725, 1140, 2752, 273 }
	end
end
do
	local player = players["srgabino"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7947, 1543, 5348, 11389 }
	end
end
do
	local player = players["rafczi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8050, 1951, 7207, 11113 }
	end
end
do
	local player = players["jynk"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6669, 2613, 9606, 213 }
	end
end
do
	local player = players["ogpivo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8215, 1128, 4452, 2156 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9993, 6, 8, 13900 }
	end
end
do
	local player = players["sendoret"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7085, 2142, 8220, 11012 }
	end
end
do
	local player = players["aladur"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7953, 1285, 5327, 1917 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7182, 2091, 7897, 11062 }
	end
end
do
	local player = players["faex"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7595, 2012, 6520, 232 }
	end
end
do
	local player = players["valyrio"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7229, 2279, 7741, 225 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9323, 456, 1070, 12281 }
	end
end
do
	local player = players["awnilove"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8938, 740, 2043, 11985 }
	end
end
do
	local player = players["issara"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8143, 1400, 4694, 11487 }
	end
end
do
	local player = players["mjret"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7409, 1948, 7140, 11147 }
	end
end
do
	local player = players["nyuui"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8460, 1541, 5331, 11364 }
	end
end
do
	local player = players["fpsko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8571, 1430, 4820, 11435 }
	end
end
do
	local player = players["habibioss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6951, 1915, 8667, 1499 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8181, 1369, 4568, 11505 }
	end
end
do
	local player = players["retribornz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9275, 500, 1189, 12241 }
	end
end
do
	local player = players["shancha"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7612, 1806, 6464, 11217 }
	end
end
do
	local player = players["admire"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9382, 410, 939, 12331 }
	end
end
do
	local player = players["hothammer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7744, 2257, 8785, 10907 }
	end
end
do
	local player = players["zegatul"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8112, 1414, 4795, 11451 }
	end
end
do
	local player = players["khattab"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7514, 1869, 6790, 11175 }
	end
end
do
	local player = players["klopik"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9829, 172, 335, 12766 }
	end
end
do
	local player = players["liilifer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9740, 261, 464, 344 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8177, 1824, 6542, 11202 }
	end
end
do
	local player = players["prohibida"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8605, 1017, 3152, 11734 }
	end
end
do
	local player = players["sykopala"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8201, 1352, 4499, 11510 }
	end
end
do
	local player = players["alainnore"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8952, 727, 1997, 11994 }
	end
end
do
	local player = players["analritter"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9415, 586, 1521, 12118 }
	end
end
do
	local player = players["illexe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9814, 187, 360, 12740 }
	end
end
do
	local player = players["swiftshield"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9216, 785, 2207, 11927 }
	end
end
do
	local player = players["xmackz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7230, 2053, 7738, 11050 }
	end
end
do
	local player = players["amwell"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9125, 603, 1565, 12123 }
	end
end
do
	local player = players["todzeropa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9495, 281, 712, 3276 }
	end
end
do
	local player = players["cinkelito"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9859, 54, 147, 3797 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9083, 792, 2222, 11946 }
	end
end
do
	local player = players["pojebiemnie"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8880, 795, 2238, 11935 }
	end
end
do
	local player = players["meowstar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8592, 1033, 3196, 11735 }
	end
end
do
	local player = players["soulcrusader"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7250, 1738, 7670, 1582 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7468, 1907, 6944, 11184 }
	end
end
do
	local player = players["marqpala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7833, 1362, 5725, 1831 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8189, 1362, 4541, 11511 }
	end
end
do
	local player = players["kamaell"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7531, 2062, 6732, 232 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8661, 974, 2966, 11780 }
	end
end
do
	local player = players["bultadin"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8640, 1226, 3036, 270 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6906, 2257, 8818, 10952 }
	end
end
do
	local player = players["isbella"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8193, 1602, 4527, 252 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8850, 694, 2337, 2792 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8501, 1108, 3500, 11683 }
	end
end
do
	local player = players["awarex"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6959, 1909, 8641, 1501 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9675, 196, 380, 12734 }
	end
end
do
	local player = players["freakzpala"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9498, 376, 705, 332 }
	end
end
do
	local player = players["auriz"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8793, 1060, 2526, 278 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7626, 1791, 6415, 11254 }
	end
end
do
	local player = players["syimik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7903, 1317, 5492, 1877 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8574, 1052, 3256, 11726 }
	end
end
do
	local player = players["loganspala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9744, 112, 284, 3577 }
	end
end
do
	local player = players["amyfowler"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9269, 591, 1206, 309 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7794, 1669, 5855, 11323 }
	end
end
do
	local player = players["otkolon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7952, 1287, 5329, 1917 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7858, 1613, 5642, 11352 }
	end
end
do
	local player = players["hulymoly"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7737, 1936, 6045, 238 }
	end
end
do
	local player = players["pvscamer"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8638, 996, 3043, 11764 }
	end
end
do
	local player = players["disturb"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7647, 1997, 6348, 235 }
	end
end
do
	local player = players["holymagnus"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9564, 283, 575, 12553 }
	end
end
do
	local player = players["airlea"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7733, 1422, 6061, 1773 }
	end
end
do
	local player = players["yukiharu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7622, 1795, 6430, 11252 }
	end
end
do
	local player = players["madgal"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7464, 2112, 6956, 231 }
	end
end
do
	local player = players["rgrgrg"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8063, 1698, 4961, 248 }
	end
end
do
	local player = players["nebroth"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7255, 2043, 7652, 11092 }
	end
end
do
	local player = players["yabadabadoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7770, 1390, 5938, 1793 }
	end
end
do
	local player = players["familijoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6948, 1917, 8675, 1499 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7169, 2102, 7939, 11056 }
	end
end
do
	local player = players["lutaria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8700, 1301, 3385, 263 }
	end
end
do
	local player = players["prooxi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8741, 1260, 3200, 266 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8898, 1103, 3533, 11654 }
	end
end
do
	local player = players["diivar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8743, 1126, 2693, 276 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8459, 1134, 3641, 11659 }
	end
end
do
	local player = players["qualiity"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8884, 965, 2223, 284 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7136, 1818, 8049, 1545 }
	end
end
do
	local player = players["repalaa"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8395, 1008, 3854, 2373 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7648, 1768, 6343, 11264 }
	end
end
do
	local player = players["saiyanmejas"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8400, 1601, 5555, 11331 }
	end
end
do
	local player = players["danathx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7091, 2367, 8201, 223 }
	end
end
do
	local player = players["drfeelgoods"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7751, 1699, 6001, 11307 }
	end
end
do
	local player = players["marradona"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7521, 1568, 6766, 1674 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7633, 1783, 6394, 11255 }
	end
end
do
	local player = players["dimhx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7497, 1587, 6847, 1663 }
	end
end
do
	local player = players["wanhedha"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9690, 200, 359, 356 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8987, 704, 1909, 12011 }
	end
end
do
	local player = players["elisen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9842, 64, 166, 3765 }
	end
end
do
	local player = players["ubivakha"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7890, 1326, 5538, 1867 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9590, 257, 521, 12584 }
	end
end
do
	local player = players["girliepopp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9800, 125, 214, 380 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9988, 8, 13, 4919 }
	end
end
do
	local player = players["powerfulk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9091, 539, 1649, 2961 }
	end
end
do
	local player = players["zaybabe"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7493, 1889, 6861, 11195 }
	end
end
do
	local player = players["armory"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8821, 710, 2433, 2768 }
	end
end
do
	local player = players["zombeepala"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6690, 2054, 9537, 1440 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8622, 1008, 3097, 11753 }
	end
end
do
	local player = players["szysz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9035, 575, 1790, 2921 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7798, 1665, 5843, 11326 }
	end
end
do
	local player = players["jungi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9396, 341, 909, 3195 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7917, 1572, 5446, 11376 }
	end
end
do
	local player = players["skovla"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7735, 1419, 6054, 1774 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8430, 1158, 3738, 11641 }
	end
end
do
	local player = players["posty"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8150, 1390, 4669, 11489 }
	end
end
do
	local player = players["dumbbkunt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9780, 95, 239, 3637 }
	end
end
do
	local player = players["janelle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 52, 374, 1523, 0 }
	end
end
do
	local player = players["vishantii"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6955, 2484, 8652, 69 }
	end
end
do
	local player = players["bluewish"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6910, 2510, 8802, 68 }
	end
end
do
	local player = players["mushmushh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1954, 337, 1232, 41 }
	end
end
do
	local player = players["relikantt"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 9025, 795, 1816, 116 }
	end
end
do
	local player = players["fakedisco"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8675, 1154, 2919, 99 }
	end
end
do
	local player = players["carinel"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7042, 2426, 8364, 70 }
	end
end
do
	local player = players["aunix"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9719, 20, 44, 193 }
	end
end
do
	local player = players["healchops"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8077, 1722, 4913, 83 }
	end
end
do
	local player = players["trahtorist"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8189, 1628, 4540, 85 }
	end
end
do
	local player = players["powersauce"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6542, 190, 530, 78 }
	end
end
do
	local player = players["tercialy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 745, 362, 1417, 11 }
	end
end
do
	local player = players["saranye"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 412, 368, 1468, 5 }
	end
end
do
	local player = players["ysirielgodx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5908, 213, 627, 73 }
	end
end
do
	local player = players["koreranattsu"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 7530, 2115, 6738, 74 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6915, 2193, 8785, 9595 }
	end
end
do
	local player = players["taano"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 5096, 4873, 26568, 7671 }
	end
end
do
	local player = players["holygirld"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7627, 142, 364, 92 }
	end
end
do
	local player = players["salni"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6885, 2213, 8886, 9583 }
	end
end
do
	local player = players["apparatus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9183, 65, 126, 132 }
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9080, 511, 1677, 10909 }
	end
end
do
	local player = players["havranplate"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9392, 49, 94, 146 }
	end
end
do
	local player = players["dversityhire"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3752, 292, 957, 59 }
	end
end
do
	local player = players["idestroy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2993, 314, 1073, 54 }
	end
end
do
	local player = players["smolroll"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3000, 313, 1072, 54 }
	end
end
do
	local player = players["aweland"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5431, 233, 700, 69 }
	end
end
do
	local player = players["drhooly"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9908, 7, 15, 283 }
	end
end
do
	local player = players["patchy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 5501, 121, 604, 7843 }
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7977, 1342, 5248, 10800 }
	end
end
do
	local player = players["yushi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4899, 136, 684, 6985 }
	end
end
do
	local player = players["hiky"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 8586, 35, 144, 10715 }
	end
end
do
	local player = players["ppc"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6932, 62, 320, 9884 }
	end
end
do
	local player = players["evilrogues"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8486, 956, 3550, 11091 }
	end
end
do
	local player = players["softndolly"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6347, 94, 468, 9050 }
	end
end
do
	local player = players["horrned"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 9853, 70, 153, 13802 }
	end
end
do
	local player = players["ocheel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2000, 5, 8, 627 }
	end
end
do
	local player = players["camejuto"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 32, 6, 9, 35 }
	end
end
do
	local player = players["pepsitwist"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 2092, 441, 2290, 3182 }
	end
end
do
	local player = players["dextershamy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 3754, 385, 1688, 5710 }
	end
end
do
	local player = players["shimona"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5031, 360, 1527, 7652 }
	end
end
do
	local player = players["ambrosiya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 5771, 316, 1341, 8778 }
	end
end
do
	local player = players["wyllz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8242, 1303, 4365, 59 }
	end
end
do
	local player = players["clytemnestra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8061, 1406, 4965, 54 }
	end
end
do
	local player = players["alejoshaman"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7052, 1969, 8331, 36 }
	end
end
do
	local player = players["shamsexual"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9554, 282, 593, 181 }
	end
end
do
	local player = players["gilena"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8341, 1230, 4033, 62 }
	end
end
do
	local player = players["sear"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8296, 1267, 4182, 60 }
	end
end
do
	local player = players["londre"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8035, 1420, 5053, 53 }
	end
end
do
	local player = players["dzonimrk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 1913, 456, 2367, 2910 }
	end
end
do
	local player = players["paluhzinho"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9101, 645, 1624, 99 }
	end
end
do
	local player = players["jhinnsoul"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 7820, 1561, 5771, 49 }
	end
end
do
	local player = players["cutepotion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 8969, 743, 1955, 91 }
	end
end
do
	local player = players["sarixd"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 9246, 524, 1263, 111 }
	end
end
do
	local player = players["tolyakolokol"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 4753, 300, 716, 8423 }
	end
end
do
	local player = players["malfoy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7783, 1353, 5892, 9833 }
	end
end
do
	local player = players["voidmender"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 6766, 1928, 9284, 9168 }
	end
end
do
	local player = players["joefskill"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 3627, 351, 822, 6428 }
	end
end
do
	local player = players["lorelai"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 8400, 942, 3838, 10308 }
	end
end
do
	local player = players["buldan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 2222, 22, 66, 2518 }
	end
end
do
	local player = players["blarrickk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 6605, 261, 868, 1177 }
	end
end
do
	local player = players["helfdane"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 6621, 35, 95, 9621 }
	end
end
do
	local player = players["scarleat"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7312, 1972, 7464, 13525 }
	end
end
do
	local player = players["gulaar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 248, 553, 2512, 213 }
	end
end
do
	local player = players["honour"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][11] = { 4213, 390, 1479, 888 }
	end
end
do
	local player = players["furysmo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][11] = { 462, 63, 208, 326 }
	end
end
do
	local player = players["hidler"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][11] = { 7938, 1512, 5376, 13825 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
