-- Auto-generated by tools/update_uwu_logs.py; do not edit by hand.
local layerKey = "togc"
local chunkStartIndex = 10295
if coolstats and coolstats.ShouldSkipUwUDataRaidLayer and coolstats.ShouldSkipUwUDataRaidLayer(coolstatsUwUData, layerKey, chunkStartIndex) then
	return
end
local players = coolstatsUwUData and coolstatsUwUData.players
if not players then
	return
end
do
	local player = players["sairus"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4713, 176, 774, 2191 }
	end
end
do
	local player = players["joelle"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5433, 53, 173, 9175 }
	end
end
do
	local player = players["yudk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3165, 315, 1456, 7910 }
	end
end
do
	local player = players["cadriel"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3520, 270, 1228, 8797 }
	end
end
do
	local player = players["pentakilo"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3454, 280, 1276, 8632 }
	end
end
do
	local player = players["iamdeadbro"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3375, 292, 1340, 8435 }
	end
end
do
	local player = players["aquari"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3445, 281, 1282, 8609 }
	end
end
do
	local player = players["wnts"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4711, 452, 2152, 8736 }
	end
end
do
	local player = players["kopsokolis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5595, 302, 1138, 10188 }
	end
end
do
	local player = players["andygreen"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7187, 234, 727, 10941 }
	end
end
do
	local player = players["buria"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9481, 61, 135, 13341 }
	end
end
do
	local player = players["moonlighta"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4632, 464, 2213, 8590 }
	end
end
do
	local player = players["teaload"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4156, 512, 2435, 7707 }
	end
end
do
	local player = players["leaf"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4934, 414, 1943, 9151 }
	end
end
do
	local player = players["bigbeer"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4176, 510, 2428, 7745 }
	end
end
do
	local player = players["sweetwood"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6118, 277, 1003, 10380 }
	end
end
do
	local player = players["melaskila"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4234, 503, 2407, 7853 }
	end
end
do
	local player = players["fuzzybear"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5050, 395, 1782, 9366 }
	end
end
do
	local player = players["amanko"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9574, 49, 111, 13585 }
	end
end
do
	local player = players["wapapa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4941, 413, 1935, 9164 }
	end
end
do
	local player = players["runehide"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4604, 468, 2231, 8540 }
	end
end
do
	local player = players["dropkar"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3716, 531, 2516, 6891 }
	end
end
do
	local player = players["bigguns"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4345, 492, 2367, 8059 }
	end
end
do
	local player = players["moonrose"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5387, 319, 1269, 9992 }
	end
end
do
	local player = players["brocoliss"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4870, 425, 2021, 9032 }
	end
end
do
	local player = players["quickshift"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4970, 409, 1897, 9218 }
	end
end
do
	local player = players["crop"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3896, 525, 2487, 7225 }
	end
end
do
	local player = players["dubolomxxl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1386, 264, 1476, 3015 }
	end
end
do
	local player = players["tiddles"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4997, 406, 1860, 9268 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2892, 258, 1453, 6292 }
	end
end
do
	local player = players["selphius"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4516, 475, 2284, 8375 }
	end
end
do
	local player = players["nalya"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6119, 26, 53, 112 }
	end
end
do
	local player = players["rudefall"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5379, 318, 1273, 9975 }
	end
end
do
	local player = players["perfectdudy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6087, 278, 1011, 10367 }
	end
end
do
	local player = players["kiszolt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7761, 15, 31, 171 }
	end
end
do
	local player = players["megafiga"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8369, 148, 422, 11852 }
	end
end
do
	local player = players["naastya"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7427, 215, 665, 11142 }
	end
end
do
	local player = players["farforina"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5411, 314, 1233, 10035 }
	end
end
do
	local player = players["yubear"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4826, 438, 2061, 8950 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5062, 202, 1016, 11014 }
	end
end
do
	local player = players["dariona"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4122, 514, 2446, 7644 }
	end
end
do
	local player = players["cascada"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5183, 191, 928, 11278 }
	end
end
do
	local player = players["nanomishka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1669, 261, 1467, 3633 }
	end
end
do
	local player = players["plus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1509, 264, 1479, 3283 }
	end
end
do
	local player = players["tireonka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4992, 207, 1066, 10863 }
	end
end
do
	local player = players["kaiita"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3151, 256, 1448, 6857 }
	end
end
do
	local player = players["vacuna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4951, 211, 1097, 10774 }
	end
end
do
	local player = players["tauraneitor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4584, 224, 1275, 9974 }
	end
end
do
	local player = players["crazypower"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4853, 216, 1152, 10561 }
	end
end
do
	local player = players["theartx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 706, 267, 1486, 1537 }
	end
end
do
	local player = players["howoldareyou"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4572, 343, 1756, 8441 }
	end
end
do
	local player = players["kyllua"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4677, 339, 1722, 8487 }
	end
end
do
	local player = players["drewsie"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3099, 465, 2919, 6314 }
	end
end
do
	local player = players["terrahlust"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7402, 216, 841, 10071 }
	end
end
do
	local player = players["trajce"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2832, 479, 3047, 5770 }
	end
end
do
	local player = players["chadter"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2980, 469, 2980, 6072 }
	end
end
do
	local player = players["ajiujiu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3218, 452, 2818, 6556 }
	end
end
do
	local player = players["alchemisst"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2960, 470, 2988, 6032 }
	end
end
do
	local player = players["kasaku"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6653, 257, 1083, 9511 }
	end
end
do
	local player = players["usopp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5070, 328, 1595, 8643 }
	end
end
do
	local player = players["dzsonbow"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7491, 209, 812, 10163 }
	end
end
do
	local player = players["galahn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3647, 420, 2428, 7432 }
	end
end
do
	local player = players["caracortada"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2635, 485, 3098, 5370 }
	end
end
do
	local player = players["escitta"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5599, 308, 1424, 8918 }
	end
end
do
	local player = players["nicklausy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3616, 426, 2466, 7368 }
	end
end
do
	local player = players["ilinka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2609, 488, 3105, 5316 }
	end
end
do
	local player = players["noralica"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7006, 238, 969, 9731 }
	end
end
do
	local player = players["dorien"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7269, 224, 884, 9967 }
	end
end
do
	local player = players["yukke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3758, 401, 2303, 7658 }
	end
end
do
	local player = players["felor"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6047, 286, 1279, 9118 }
	end
end
do
	local player = players["floarea"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5654, 306, 1406, 8947 }
	end
end
do
	local player = players["futensteiin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3074, 467, 2939, 6264 }
	end
end
do
	local player = players["neverknowme"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5026, 330, 1609, 8623 }
	end
end
do
	local player = players["kneeshot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5342, 321, 1507, 8786 }
	end
end
do
	local player = players["farkos"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7303, 222, 873, 9991 }
	end
end
do
	local player = players["prytok"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7358, 220, 855, 10043 }
	end
end
do
	local player = players["joslyn"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7473, 212, 818, 10136 }
	end
end
do
	local player = players["xiaopengyou"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7705, 191, 743, 10305 }
	end
end
do
	local player = players["milev"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3213, 455, 2822, 6547 }
	end
end
do
	local player = players["tooldforthis"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3991, 371, 1988, 8132 }
	end
end
do
	local player = players["frenzyaged"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7111, 231, 935, 9826 }
	end
end
do
	local player = players["alleno"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5753, 427, 1673, 12908 }
	end
end
do
	local player = players["eltanin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6273, 378, 1429, 13209 }
	end
end
do
	local player = players["massiveballz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5295, 567, 2589, 11881 }
	end
end
do
	local player = players["hopediamond"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8348, 179, 634, 15100 }
	end
end
do
	local player = players["strig"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5850, 413, 1591, 13002 }
	end
end
do
	local player = players["tucarios"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5752, 428, 1675, 12907 }
	end
end
do
	local player = players["ignatius"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7369, 286, 1009, 13942 }
	end
end
do
	local player = players["tisseneant"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5012, 609, 3031, 11247 }
	end
end
do
	local player = players["bigprick"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5434, 532, 2306, 12192 }
	end
end
do
	local player = players["shierra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7264, 294, 1049, 13860 }
	end
end
do
	local player = players["quillen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4821, 640, 3259, 10818 }
	end
end
do
	local player = players["fuegoletal"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8684, 152, 505, 15500 }
	end
end
do
	local player = players["spiike"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7032, 324, 1138, 13706 }
	end
end
do
	local player = players["slashspit"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5514, 510, 2143, 12373 }
	end
end
do
	local player = players["magiclight"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8040, 219, 752, 14651 }
	end
end
do
	local player = players["laxruffrydam"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5340, 550, 2488, 11982 }
	end
end
do
	local player = players["snowist"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6549, 361, 1323, 13354 }
	end
end
do
	local player = players["etka"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5319, 558, 2533, 11934 }
	end
end
do
	local player = players["yonkosteel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4972, 618, 3089, 11157 }
	end
end
do
	local player = players["abrakadaber"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5593, 483, 1982, 12550 }
	end
end
do
	local player = players["alderaan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5634, 468, 1902, 12641 }
	end
end
do
	local player = players["onion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4614, 664, 3450, 10352 }
	end
end
do
	local player = players["trebinol"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5008, 610, 3038, 11237 }
	end
end
do
	local player = players["synthetic"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6523, 364, 1333, 13341 }
	end
end
do
	local player = players["gnomehables"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9052, 108, 364, 16092 }
	end
end
do
	local player = players["mereoleona"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9214, 93, 302, 16404 }
	end
end
do
	local player = players["tekki"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4721, 655, 3360, 10593 }
	end
end
do
	local player = players["magipula"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7993, 225, 770, 14598 }
	end
end
do
	local player = players["startukas"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4561, 673, 3496, 10234 }
	end
end
do
	local player = players["sunstorm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5847, 414, 1592, 13002 }
	end
end
do
	local player = players["kyrae"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8523, 167, 567, 15279 }
	end
end
do
	local player = players["ultea"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6395, 370, 1382, 13267 }
	end
end
do
	local player = players["smallproblem"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5524, 506, 2125, 12396 }
	end
end
do
	local player = players["avvhore"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5244, 579, 2678, 11767 }
	end
end
do
	local player = players["nevona"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5283, 571, 2607, 11855 }
	end
end
do
	local player = players["preta"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5295, 568, 2590, 11881 }
	end
end
do
	local player = players["csizmike"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6721, 347, 1257, 13465 }
	end
end
do
	local player = players["fervion"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7361, 287, 1012, 13936 }
	end
end
do
	local player = players["critsbro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5486, 519, 2202, 12310 }
	end
end
do
	local player = players["heahmund"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7661, 262, 897, 14273 }
	end
end
do
	local player = players["sylver"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5592, 484, 1986, 12547 }
	end
end
do
	local player = players["amethara"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5288, 569, 2596, 11866 }
	end
end
do
	local player = players["myocardium"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4992, 611, 3058, 11201 }
	end
end
do
	local player = players["pyrodogx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6557, 358, 1320, 13364 }
	end
end
do
	local player = players["critshockx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6476, 366, 1351, 13310 }
	end
end
do
	local player = players["zserbote"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6447, 368, 1362, 13294 }
	end
end
do
	local player = players["sukme"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5016, 607, 3022, 11255 }
	end
end
do
	local player = players["jlolj"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9217, 92, 301, 16404 }
	end
end
do
	local player = players["rodiboss"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4986, 613, 3069, 11187 }
	end
end
do
	local player = players["wingz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5121, 592, 2870, 11490 }
	end
end
do
	local player = players["scallyweg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7079, 318, 1120, 13733 }
	end
end
do
	local player = players["abalar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6032, 399, 1521, 13083 }
	end
end
do
	local player = players["mephire"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4980, 616, 3078, 11175 }
	end
end
do
	local player = players["themamba"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4631, 663, 3437, 10390 }
	end
end
do
	local player = players["asaf"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5713, 439, 1751, 12820 }
	end
end
do
	local player = players["zawavari"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5671, 455, 1826, 12724 }
	end
end
do
	local player = players["sdjin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8335, 180, 639, 15071 }
	end
end
do
	local player = players["zauber"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7828, 244, 833, 14445 }
	end
end
do
	local player = players["dreamgiirll"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6202, 384, 1456, 13176 }
	end
end
do
	local player = players["emynth"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6314, 375, 1413, 13231 }
	end
end
do
	local player = players["pantich"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4819, 641, 3263, 10812 }
	end
end
do
	local player = players["magi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3776, 706, 3733, 8473 }
	end
end
do
	local player = players["saine"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5336, 552, 2496, 11973 }
	end
end
do
	local player = players["electrah"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5392, 540, 2390, 12099 }
	end
end
do
	local player = players["bluberi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5565, 491, 2040, 12487 }
	end
end
do
	local player = players["xperya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5094, 596, 2911, 11430 }
	end
end
do
	local player = players["brainpp"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5027, 604, 3003, 11280 }
	end
end
do
	local player = players["riln"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4819, 642, 3264, 10812 }
	end
end
do
	local player = players["lexlootwhr"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4779, 648, 3308, 10723 }
	end
end
do
	local player = players["lallypop"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7228, 299, 1063, 13833 }
	end
end
do
	local player = players["dobru"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6077, 395, 1504, 13100 }
	end
end
do
	local player = players["elegan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4831, 636, 3245, 10839 }
	end
end
do
	local player = players["icetouched"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5644, 464, 1873, 12665 }
	end
end
do
	local player = players["saintess"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4645, 661, 3425, 10423 }
	end
end
do
	local player = players["elmar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9253, 88, 287, 16487 }
	end
end
do
	local player = players["maago"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5458, 525, 2256, 12247 }
	end
end
do
	local player = players["impress"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8237, 6, 8, 10326 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8108, 211, 726, 14742 }
	end
end
do
	local player = players["wvrlxrd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4502, 319, 1078, 163 }
	end
end
do
	local player = players["biszkopcik"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 263, 439, 1924, 57 }
	end
end
do
	local player = players["marrone"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8479, 121, 299, 257 }
	end
end
do
	local player = players["rokfmrd"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2164, 400, 1536, 124 }
	end
end
do
	local player = players["kessinka"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3941, 345, 1188, 153 }
	end
end
do
	local player = players["evoque"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7779, 164, 436, 230 }
	end
end
do
	local player = players["skyseeker"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5745, 452, 1834, 10311 }
	end
end
do
	local player = players["obrigado"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8423, 124, 310, 254 }
	end
end
do
	local player = players["curufin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5266, 545, 2546, 9681 }
	end
end
do
	local player = players["corax"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6631, 222, 661, 201 }
	end
end
do
	local player = players["xiaolemon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5120, 587, 2819, 9413 }
	end
end
do
	local player = players["qetsyiah"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3155, 367, 1342, 141 }
	end
end
do
	local player = players["tomorrowland"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4487, 320, 1081, 162 }
	end
end
do
	local player = players["nutrix"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1087, 416, 1747, 100 }
	end
end
do
	local player = players["xooxy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 934, 419, 1777, 96 }
	end
end
do
	local player = players["alantis"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3798, 350, 1216, 150 }
	end
end
do
	local player = players["lunau"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3673, 779, 4147, 6752 }
	end
end
do
	local player = players["kumo"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 311, 435, 1899, 68 }
	end
end
do
	local player = players["sealsayy"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7570, 174, 477, 223 }
	end
end
do
	local player = players["hunzz"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4464, 720, 3738, 8207 }
	end
end
do
	local player = players["holyshift"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 674, 428, 1828, 86 }
	end
end
do
	local player = players["doben"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6158, 427, 1656, 10469 }
	end
end
do
	local player = players["ziko"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9081, 162, 397, 12388 }
	end
end
do
	local player = players["cupcake"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4461, 721, 3740, 8202 }
	end
end
do
	local player = players["ariael"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4982, 620, 3074, 9159 }
	end
end
do
	local player = players["freevideos"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8025, 293, 852, 11330 }
	end
end
do
	local player = players["yabuki"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4683, 685, 3500, 8609 }
	end
end
do
	local player = players["koralia"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4983, 619, 3072, 9160 }
	end
end
do
	local player = players["levay"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7096, 377, 1252, 10847 }
	end
end
do
	local player = players["murrayy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7809, 312, 945, 11207 }
	end
end
do
	local player = players["eldaren"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5847, 446, 1790, 10351 }
	end
end
do
	local player = players["ndiq"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5516, 476, 2022, 10140 }
	end
end
do
	local player = players["augi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5207, 560, 2649, 9573 }
	end
end
do
	local player = players["ouejih"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8429, 247, 678, 11645 }
	end
end
do
	local player = players["pikaper"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5172, 571, 2723, 9508 }
	end
end
do
	local player = players["persival"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8700, 213, 561, 11887 }
	end
end
do
	local player = players["palkali"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4844, 650, 3292, 8905 }
	end
end
do
	local player = players["brosader"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8357, 254, 709, 11586 }
	end
end
do
	local player = players["egirllover"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5124, 585, 2811, 9419 }
	end
end
do
	local player = players["ripraven"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4714, 679, 3454, 8666 }
	end
end
do
	local player = players["cicatrys"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7567, 339, 1049, 11082 }
	end
end
do
	local player = players["kushiina"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4625, 697, 3578, 8503 }
	end
end
do
	local player = players["kvrdk"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5136, 583, 2790, 9442 }
	end
end
do
	local player = players["rashamba"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6465, 413, 1524, 10584 }
	end
end
do
	local player = players["bnt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9255, 137, 322, 12678 }
	end
end
do
	local player = players["puvu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8507, 233, 644, 11721 }
	end
end
do
	local player = players["meiyangyang"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7136, 373, 1235, 10863 }
	end
end
do
	local player = players["luzs"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5298, 536, 2479, 9740 }
	end
end
do
	local player = players["daixiahu"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6792, 394, 1383, 10728 }
	end
end
do
	local player = players["blue"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4995, 616, 3048, 9183 }
	end
end
do
	local player = players["dashila"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8617, 224, 597, 11824 }
	end
end
do
	local player = players["amonhamatt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9427, 110, 248, 12966 }
	end
end
do
	local player = players["compassion"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7136, 373, 1235, 10863 }
	end
end
do
	local player = players["kimezin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5172, 569, 2719, 9509 }
	end
end
do
	local player = players["msbiitchy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9336, 124, 287, 12785 }
	end
end
do
	local player = players["jadakiss"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5386, 506, 2300, 9901 }
	end
end
do
	local player = players["mistgorila"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5980, 437, 1733, 10400 }
	end
end
do
	local player = players["diffra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5042, 607, 2969, 9270 }
	end
end
do
	local player = players["balamyt"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5023, 610, 3000, 9235 }
	end
end
do
	local player = players["impories"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5189, 563, 2685, 9540 }
	end
end
do
	local player = players["kubapala"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5300, 534, 2469, 9744 }
	end
end
do
	local player = players["alefeholy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5666, 455, 1868, 10284 }
	end
end
do
	local player = players["shurka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3094, 789, 4213, 5689 }
	end
end
do
	local player = players["hollyn"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5249, 549, 2572, 9649 }
	end
end
do
	local player = players["trimskualpro"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5374, 509, 2321, 9880 }
	end
end
do
	local player = players["tmxpink"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 8918, 87, 213, 279 }
	end
end
do
	local player = players["dranpaly"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5537, 470, 1982, 10180 }
	end
end
do
	local player = players["nurka"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4622, 698, 3583, 8497 }
	end
end
do
	local player = players["pipidin"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6706, 399, 1420, 10693 }
	end
end
do
	local player = players["aimp"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5355, 517, 2362, 9845 }
	end
end
do
	local player = players["khaelh"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8995, 170, 434, 12254 }
	end
end
do
	local player = players["samknight"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7066, 379, 1265, 10827 }
	end
end
do
	local player = players["anasterian"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4310, 745, 3892, 7924 }
	end
end
do
	local player = players["veryfast"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 7070, 196, 575, 211 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8582, 227, 612, 11785 }
	end
end
do
	local player = players["medilena"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5211, 559, 2642, 9580 }
	end
end
do
	local player = players["plan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4072, 761, 4013, 7486 }
	end
end
do
	local player = players["veritass"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4318, 743, 3885, 7938 }
	end
end
do
	local player = players["whisprush"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4788, 166, 555, 116 }
	end
end
do
	local player = players["merisa"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 6058, 125, 420, 133 }
	end
end
do
	local player = players["rohanp"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 1919, 234, 860, 73 }
	end
end
do
	local player = players["bogojebac"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 310, 256, 1031, 2 }
	end
end
do
	local player = players["jadi"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 3151, 213, 729, 97 }
	end
end
do
	local player = players["maryanne"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 9426, 26, 62, 792 }
	end
end
do
	local player = players["reality"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 3492, 429, 1955, 6292 }
	end
end
do
	local player = players["fallsunset"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 2813, 218, 765, 91 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4294, 422, 1928, 7738 }
	end
end
do
	local player = players["halomoon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 7867, 142, 422, 13189 }
	end
end
do
	local player = players["moghan"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5736, 346, 1497, 10336 }
	end
end
do
	local player = players["trollgoggy"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4766, 409, 1887, 8589 }
	end
end
do
	local player = players["feorra"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6353, 253, 891, 11447 }
	end
end
do
	local player = players["rusroma"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6613, 219, 710, 11916 }
	end
end
do
	local player = players["besana"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5099, 397, 1820, 9187 }
	end
end
do
	local player = players["ishmi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5793, 338, 1445, 10438 }
	end
end
do
	local player = players["platinum"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5618, 357, 1595, 10122 }
	end
end
do
	local player = players["yukee"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4643, 416, 1905, 8366 }
	end
end
do
	local player = players["okrw"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5914, 317, 1297, 10657 }
	end
end
do
	local player = players["ikon"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5227, 389, 1771, 9419 }
	end
end
do
	local player = players["spl"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6353, 252, 890, 11448 }
	end
end
do
	local player = players["ihatom"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6754, 194, 645, 12170 }
	end
end
do
	local player = players["prokaznica"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 6732, 199, 658, 12131 }
	end
end
do
	local player = players["kavliaara"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 5199, 392, 1780, 9368 }
	end
end
do
	local player = players["cobrapwnx"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4923, 405, 1863, 8871 }
	end
end
do
	local player = players["amonshin"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4872, 351, 1481, 11090 }
	end
end
do
	local player = players["synaxis"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3069, 531, 2846, 7106 }
	end
end
do
	local player = players["euphoriaz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4699, 376, 1658, 10878 }
	end
end
do
	local player = players["toxlc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4086, 491, 2598, 9459 }
	end
end
do
	local player = players["hauu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4111, 488, 2576, 9518 }
	end
end
do
	local player = players["mutilar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4075, 494, 2605, 9435 }
	end
end
do
	local player = players["anexyrog"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4535, 421, 1990, 10499 }
	end
end
do
	local player = players["zherneboh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4986, 345, 1448, 11124 }
	end
end
do
	local player = players["boyoz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4213, 479, 2487, 9754 }
	end
end
do
	local player = players["klaksik"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5246, 335, 1373, 11200 }
	end
end
do
	local player = players["ripsexo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8971, 98, 298, 13917 }
	end
end
do
	local player = players["zectro"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4569, 412, 1915, 10577 }
	end
end
do
	local player = players["thielsen"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4726, 368, 1610, 10941 }
	end
end
do
	local player = players["wolverinne"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3728, 515, 2764, 8631 }
	end
end
do
	local player = players["fakeyou"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4409, 450, 2232, 10209 }
	end
end
do
	local player = players["lesindra"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5859, 303, 1196, 11428 }
	end
end
do
	local player = players["lisk"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4428, 445, 2184, 10251 }
	end
end
do
	local player = players["baccker"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 1283, 542, 2878, 2970 }
	end
end
do
	local player = players["trajieziia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4369, 463, 2312, 10116 }
	end
end
do
	local player = players["chocdeadmom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4760, 361, 1553, 11019 }
	end
end
do
	local player = players["okinagedva"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5620, 312, 1265, 11342 }
	end
end
do
	local player = players["antimagee"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4067, 496, 2610, 9415 }
	end
end
do
	local player = players["gatheg"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4237, 475, 2456, 9809 }
	end
end
do
	local player = players["ppashtet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7346, 207, 767, 12275 }
	end
end
do
	local player = players["shangke"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4140, 483, 2545, 9584 }
	end
end
do
	local player = players["iamoxy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3229, 530, 2836, 7475 }
	end
end
do
	local player = players["exolt"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7876, 175, 614, 12719 }
	end
end
do
	local player = players["orpheya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4233, 476, 2462, 9800 }
	end
end
do
	local player = players["myrmidon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5509, 319, 1297, 11307 }
	end
end
do
	local player = players["kysi"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2540, 268, 835, 18 }
	end
end
do
	local player = players["cptshaggy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8554, 9, 13, 11010 }
	end
end
do
	local player = players["guenwar"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 2039, 277, 891, 13 }
	end
end
do
	local player = players["coolness"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 5347, 28, 46, 7164 }
	end
end
do
	local player = players["drmob"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 98, 318, 1108, 0 }
	end
end
do
	local player = players["earthcoil"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 4213, 227, 648, 35 }
	end
end
do
	local player = players["natty"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 188, 315, 1100, 0 }
	end
end
do
	local player = players["oldforthis"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8631, 67, 154, 242 }
	end
end
do
	local player = players["dotandgoseek"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7709, 123, 355, 12177 }
	end
end
do
	local player = players["hybridx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3927, 350, 1470, 8092 }
	end
end
do
	local player = players["enir"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4563, 317, 1297, 9402 }
	end
end
do
	local player = players["xades"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4325, 332, 1388, 8912 }
	end
end
do
	local player = players["nomabald"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 2011, 367, 1533, 4145 }
	end
end
do
	local player = players["krolikxxh"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4484, 322, 1335, 9241 }
	end
end
do
	local player = players["qlm"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3951, 348, 1467, 8142 }
	end
end
do
	local player = players["monkx"]
	if player then
		player[9] = player[9] or {}
		player[9][1] = player[9][1] or {}
			player[9][1][12] = { 4286, 126, 362, 9278 }
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4690, 302, 1212, 9665 }
	end
end
do
	local player = players["cursebot"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3916, 351, 1475, 8070 }
	end
end
do
	local player = players["coup"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5470, 500, 2762, 11100 }
	end
end
do
	local player = players["yixo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5358, 516, 2959, 10873 }
	end
end
do
	local player = players["californya"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5239, 535, 3139, 10631 }
	end
end
do
	local player = players["fiorene"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7173, 302, 1115, 12830 }
	end
end
do
	local player = players["ebaniscumer"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4976, 559, 3428, 10097 }
	end
end
do
	local player = players["kracimira"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9066, 146, 369, 14476 }
	end
end
do
	local player = players["deadlyfury"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7706, 260, 905, 13212 }
	end
end
do
	local player = players["icc"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4978, 558, 3423, 10102 }
	end
end
do
	local player = players["asklit"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5801, 427, 2082, 11770 }
	end
end
do
	local player = players["zibathy"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7662, 265, 922, 13175 }
	end
end
do
	local player = players["erza"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6368, 351, 1432, 12438 }
	end
end
do
	local player = players["sugimori"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6277, 356, 1468, 12389 }
	end
end
do
	local player = players["kraba"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5720, 448, 2271, 11607 }
	end
end
do
	local player = players["onlydollar"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4277, 608, 3763, 8680 }
	end
end
do
	local player = players["anathis"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5760, 433, 2172, 11687 }
	end
end
do
	local player = players["angrypixels"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5845, 417, 1986, 11861 }
	end
end
do
	local player = players["kinkupizax"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5248, 534, 3128, 10649 }
	end
end
do
	local player = players["acd"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4932, 563, 3462, 10009 }
	end
end
do
	local player = players["alhirim"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5284, 523, 3063, 10723 }
	end
end
do
	local player = players["ainima"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6937, 320, 1208, 12706 }
	end
end
do
	local player = players["zzeroo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8089, 231, 754, 13506 }
	end
end
do
	local player = players["auronnx"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7079, 312, 1152, 12784 }
	end
end
do
	local player = players["naios"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5865, 413, 1949, 11901 }
	end
end
do
	local player = players["fuzeten"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6609, 343, 1337, 12549 }
	end
end
do
	local player = players["oficirsruzom"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4756, 579, 3580, 9650 }
	end
end
do
	local player = players["yellooww"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7695, 261, 909, 13206 }
	end
end
do
	local player = players["dimyna"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5450, 504, 2797, 11060 }
	end
end
do
	local player = players["testosteronu"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6051, 370, 1566, 12279 }
	end
end
do
	local player = players["competition"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4916, 565, 3476, 9976 }
	end
end
do
	local player = players["pharaho"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5212, 537, 3169, 10577 }
	end
end
do
	local player = players["roidz"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5824, 422, 2026, 11819 }
	end
end
do
	local player = players["melperon"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4954, 561, 3449, 10053 }
	end
end
do
	local player = players["drexel"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5422, 508, 2857, 11002 }
	end
end
do
	local player = players["gorlais"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5446, 505, 2806, 11051 }
	end
end
do
	local player = players["knyl"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 7261, 297, 1080, 12887 }
	end
end
do
	local player = players["bloodymess"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5746, 439, 2209, 11661 }
	end
end
do
	local player = players["inviqtum"]
	if player then
		player[9] = player[9] or {}
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 8635, 33, 175, 27072 }
	end
end
do
	local player = players["marcellinus"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5166, 544, 3235, 10482 }
	end
end
do
	local player = players["sareniicvet"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5173, 543, 3224, 10496 }
	end
end
do
	local player = players["balls"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8584, 195, 559, 13987 }
	end
end
do
	local player = players["alistan"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5451, 503, 2796, 11060 }
	end
end
do
	local player = players["yamakashi"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5692, 453, 2323, 11550 }
	end
end
do
	local player = players["lilty"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 8025, 234, 779, 13456 }
	end
end
do
	local player = players["ajazhui"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6050, 371, 1568, 12276 }
	end
end
do
	local player = players["enragedfury"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5152, 546, 3249, 10454 }
	end
end
do
	local player = players["addam"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3543, 632, 3862, 7189 }
	end
end
do
	local player = players["vudoo"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6000, 381, 1666, 12175 }
	end
end
do
	local player = players["jil"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 9414, 96, 232, 14980 }
	end
end
do
	local player = players["xalira"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4185, 614, 3781, 8492 }
		player[9][3] = player[9][3] or {}
			player[9][3][12] = { 9310, 17, 89, 32080 }
	end
end
do
	local player = players["darkey"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5308, 519, 3028, 10770 }
	end
end
do
	local player = players["sorcery"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5975, 386, 1720, 12125 }
	end
end
do
	local player = players["exded"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5184, 541, 3208, 10520 }
	end
end
do
	local player = players["tzunder"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 3805, 628, 3828, 7721 }
	end
end
do
	local player = players["baret"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 5619, 470, 2477, 11401 }
	end
end
do
	local player = players["warhoofs"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 6338, 352, 1444, 12415 }
	end
end
do
	local player = players["cornelia"]
	if player then
		player[9] = player[9] or {}
		player[9][2] = player[9][2] or {}
			player[9][2][12] = { 4068, 619, 3797, 8256 }
	end
end
if coolstats and coolstats.MarkUwUDataRaidLayerLoaded then
	coolstats.MarkUwUDataRaidLayerLoaded(coolstatsUwUData, layerKey, chunkStartIndex)
end
